{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "widgets",
    "version": "0.0.1.21051816-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "aoeg7thp2jgfbn2ajukzcuouki"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.21051816-SNAPSHOT.aar",
          "url": "widgets-0.0.1.21051816-20210518.084648-1.aar",
          "size": 28208,
          "sha512": "f12d95a7a892810a294b10bd04459d10a1342a533807cd91acb3ac6dff2dec70e5581d6a5c68284f9daf5eb2f7893f2dea4c470608ac30dc68f71faadcbf8112",
          "sha256": "b23321bb13b7447ddbdf1eab7a742b780bcb0d0df2a17b9972e1240f441938e6",
          "sha1": "5557b12bbec9cfc5cf0f0e2b4980e0dd4460f613",
          "md5": "b59f827f7338aef54266c4937798c4a3"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.21051816-SNAPSHOT.aar",
          "url": "widgets-0.0.1.21051816-20210518.084648-1.aar",
          "size": 28208,
          "sha512": "f12d95a7a892810a294b10bd04459d10a1342a533807cd91acb3ac6dff2dec70e5581d6a5c68284f9daf5eb2f7893f2dea4c470608ac30dc68f71faadcbf8112",
          "sha256": "b23321bb13b7447ddbdf1eab7a742b780bcb0d0df2a17b9972e1240f441938e6",
          "sha1": "5557b12bbec9cfc5cf0f0e2b4980e0dd4460f613",
          "md5": "b59f827f7338aef54266c4937798c4a3"
        }
      ]
    }
  ]
}
