{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.22031622-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "fnli6vtqjfhwnlxkx3cbvc6pre"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.22031622-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.22031622-20220616.145012-1.aar",
          "size": 50930,
          "sha512": "2ef4102569b83aab2536e08a2b2004df8d2342cb17042f05b4ae738d059569d80bd1bccd8b6dcab4ca03c38a914649e5a12868ec33b3156e21fd67251b6f59dc",
          "sha256": "87e4f192ff3280e1c92942685825a3369f51399399381ca6446910c0166a6d47",
          "sha1": "0b4dc5422325fe9f3c4b5468ae906e799e2d25b9",
          "md5": "cb64838383c36e8fc220b30eb314704a"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.22031622-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.22031622-20220616.145012-1.aar",
          "size": 50930,
          "sha512": "2ef4102569b83aab2536e08a2b2004df8d2342cb17042f05b4ae738d059569d80bd1bccd8b6dcab4ca03c38a914649e5a12868ec33b3156e21fd67251b6f59dc",
          "sha256": "87e4f192ff3280e1c92942685825a3369f51399399381ca6446910c0166a6d47",
          "sha1": "0b4dc5422325fe9f3c4b5468ae906e799e2d25b9",
          "md5": "cb64838383c36e8fc220b30eb314704a"
        }
      ]
    }
  ]
}
