{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "i7yzb2rgmbd67ht37e2cot2a7u"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.4.aar",
          "url": "common-0.0.4.aar",
          "size": 21797,
          "sha512": "e05faf9c38d38f53f9777b39d9bb0f9a10e6d4a850721792a94cbbdc7c75423aac67dc6b3034b050b21bca38f7f46f0a048a90d1394e3f95ac2c2eeed9802799",
          "sha256": "240107e5fc720fdd60a0a5da3dbfaebf5d7242d0c132087dbd56089d5b97222f",
          "sha1": "219e3b7eda47f9506b77385ed506bbf58ef7dbb1",
          "md5": "98fe7d6e50eecc838312ac1e1a152aef"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.4.aar",
          "url": "common-0.0.4.aar",
          "size": 21797,
          "sha512": "e05faf9c38d38f53f9777b39d9bb0f9a10e6d4a850721792a94cbbdc7c75423aac67dc6b3034b050b21bca38f7f46f0a048a90d1394e3f95ac2c2eeed9802799",
          "sha256": "240107e5fc720fdd60a0a5da3dbfaebf5d7242d0c132087dbd56089d5b97222f",
          "sha1": "219e3b7eda47f9506b77385ed506bbf58ef7dbb1",
          "md5": "98fe7d6e50eecc838312ac1e1a152aef"
        }
      ]
    }
  ]
}
