{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22072501-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kx25kxzsvrcabc2mcznwgfxmfe"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22072501-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22072501-20220724.175617-1.aar",
          "size": 164113,
          "sha512": "addd71182ea74279c6fff46e949e2da7a4cd0b33ff2a564c6713fbcdb716e41c7c52ba035fd7cea010b2d154a0dca42c3873f2687dcb4876926b27dc63070c00",
          "sha256": "4f3cf43b5ccdb499864fdcedc56258aabc59c47f21044b143ed0d103c7558de4",
          "sha1": "f6408479919324daf05225325e37e8dbf445503f",
          "md5": "203619a3781abc8e97af79375fce9bb4"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22071000-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22072501-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22072501-20220724.175617-1.aar",
          "size": 164113,
          "sha512": "addd71182ea74279c6fff46e949e2da7a4cd0b33ff2a564c6713fbcdb716e41c7c52ba035fd7cea010b2d154a0dca42c3873f2687dcb4876926b27dc63070c00",
          "sha256": "4f3cf43b5ccdb499864fdcedc56258aabc59c47f21044b143ed0d103c7558de4",
          "sha1": "f6408479919324daf05225325e37e8dbf445503f",
          "md5": "203619a3781abc8e97af79375fce9bb4"
        }
      ]
    }
  ]
}
