{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "m2jlvlrcybaopb2nh63szzuk3e"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.083944-2.aar",
          "size": 128565,
          "sha512": "7d31b01ecf5b74197beae940d18576bdd3a7471f09224e49b8600aae64adb783e3e8ceaa45748983a79762f2f49d605f397adcbd726a13587bbdf6b8a925131f",
          "sha256": "7b2c9bcd744234e30c2832c1af1d3f73fc8ea779001a79841010bc4ad1d08554",
          "sha1": "99af3fe5f54cfb1d0568029d4c4170638a6bbba4",
          "md5": "4dd9a4f6cf436166c9410dca334c3fe1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.083944-2.aar",
          "size": 128565,
          "sha512": "7d31b01ecf5b74197beae940d18576bdd3a7471f09224e49b8600aae64adb783e3e8ceaa45748983a79762f2f49d605f397adcbd726a13587bbdf6b8a925131f",
          "sha256": "7b2c9bcd744234e30c2832c1af1d3f73fc8ea779001a79841010bc4ad1d08554",
          "sha1": "99af3fe5f54cfb1d0568029d4c4170638a6bbba4",
          "md5": "4dd9a4f6cf436166c9410dca334c3fe1"
        }
      ]
    }
  ]
}
