{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nd52jkz7qrfv7dfqh3o75bgqwe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6.aar",
          "url": "recyclerview-0.9.6.aar",
          "size": 125232,
          "sha512": "d1e0f634408abe35361265b61f8e391d774fa077ac0c29009a958c5a4a2d7cc13473ebea0337ba31a1c6b98033dbb060371df50fc6bf46d8033c651faa962d34",
          "sha256": "7d9cf53d1c5dad4013317793ea54b8fe1494c5f88827740e2fc5f84199081a15",
          "sha1": "fb682700f02f7c4b93093c4309fe5183f4a843d5",
          "md5": "0bc20a20c45342f510361b6841dc7f9e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6.aar",
          "url": "recyclerview-0.9.6.aar",
          "size": 125232,
          "sha512": "d1e0f634408abe35361265b61f8e391d774fa077ac0c29009a958c5a4a2d7cc13473ebea0337ba31a1c6b98033dbb060371df50fc6bf46d8033c651faa962d34",
          "sha256": "7d9cf53d1c5dad4013317793ea54b8fe1494c5f88827740e2fc5f84199081a15",
          "sha1": "fb682700f02f7c4b93093c4309fe5183f4a843d5",
          "md5": "0bc20a20c45342f510361b6841dc7f9e"
        }
      ]
    }
  ]
}
