{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rmvem3j5obck3ou6wfdribly5i"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201027.132824-9.aar",
          "size": 36728,
          "sha512": "d921c601df7117308c58492a921245db986e2785867e8f09108d476642a61e52618c182b54ecb1bfd409ca57379bf19a39aa4b231caabea8d3e3f9b9740bd19e",
          "sha256": "df1678a4d651760948620e06147798139e37e728ed2f4fed3f4fee70841441a8",
          "sha1": "3041412180d673fd006ec967d15edd8f592e825d",
          "md5": "380e0d46d99c4ba324b7270494326d21"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201027.132824-9.aar",
          "size": 36728,
          "sha512": "d921c601df7117308c58492a921245db986e2785867e8f09108d476642a61e52618c182b54ecb1bfd409ca57379bf19a39aa4b231caabea8d3e3f9b9740bd19e",
          "sha256": "df1678a4d651760948620e06147798139e37e728ed2f4fed3f4fee70841441a8",
          "sha1": "3041412180d673fd006ec967d15edd8f592e825d",
          "md5": "380e0d46d99c4ba324b7270494326d21"
        }
      ]
    }
  ]
}
