{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.21110720-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yzctrdnxnzdc5aor4nmgod74aq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110720-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110720-20211107.110217-1.aar",
          "size": 122973,
          "sha512": "add4cf1fa0d1b018cb030f932f36a7ac5cf20d0d2afc3f9c9f66cd0d27965f10138725408209308a69bc4f72c0ea703d68b72ea1e30aab6a8e07631c95b483eb",
          "sha256": "c78e447bfc68041797e0d02f42e72b1c64da0a4197909f92c55d13330d509702",
          "sha1": "69c04701e8f9f4d6430b691a6728155a8ad7868c",
          "md5": "202dcdf817aeb0dba119bdde2bbe7763"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110720-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110720-20211107.110217-1.aar",
          "size": 122973,
          "sha512": "add4cf1fa0d1b018cb030f932f36a7ac5cf20d0d2afc3f9c9f66cd0d27965f10138725408209308a69bc4f72c0ea703d68b72ea1e30aab6a8e07631c95b483eb",
          "sha256": "c78e447bfc68041797e0d02f42e72b1c64da0a4197909f92c55d13330d509702",
          "sha1": "69c04701e8f9f4d6430b691a6728155a8ad7868c",
          "md5": "202dcdf817aeb0dba119bdde2bbe7763"
        }
      ]
    }
  ]
}
