{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.0.21011920-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "3v62eken35gkxpofqjf3ol4kaa"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.0.21011920-SNAPSHOT.aar",
          "url": "json-dsl-0.2.0.21011920-20210119.124952-1.aar",
          "size": 39875,
          "sha512": "b176e7ce7c9793b5a0b22299a7f2da031b2ff585610f5523f7bf5f5152b8a7ab8ae618f20ce4928fda43029e0173340572752aa062a069c93c350d70bf212090",
          "sha256": "9bb649b9d511db4d682af54102d6c62ed9622bf362d4897389ba60de6825c82b",
          "sha1": "af1dbddc35864c8b5cd4709b4856f4da5189f072",
          "md5": "b30ef6a0c1bc1dbb2fdd1e74c0de35c2"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.0.21011920-SNAPSHOT.aar",
          "url": "json-dsl-0.2.0.21011920-20210119.124952-1.aar",
          "size": 39875,
          "sha512": "b176e7ce7c9793b5a0b22299a7f2da031b2ff585610f5523f7bf5f5152b8a7ab8ae618f20ce4928fda43029e0173340572752aa062a069c93c350d70bf212090",
          "sha256": "9bb649b9d511db4d682af54102d6c62ed9622bf362d4897389ba60de6825c82b",
          "sha1": "af1dbddc35864c8b5cd4709b4856f4da5189f072",
          "md5": "b30ef6a0c1bc1dbb2fdd1e74c0de35c2"
        }
      ]
    }
  ]
}
