{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "wfmpq63o4bcl7l2e5ufviydh5m"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201019.150510-12.aar",
          "size": 119560,
          "sha512": "fb02f3a984485d36bf9794dcfcb935245509c8bbc3b886dfa8dccd8f594b5636da6f5965bbf5c5addb0aeeeffd74392e61e68d6bb9a599f82d33a41641969143",
          "sha256": "b811fc1ea38f34d0fbeb9a5b56f13ea6805ee8bf10a410350b23efd3a738d48d",
          "sha1": "0cf10d294e8b8a67376615a1e402229ce70e66fe",
          "md5": "7b09743afa729c93f0f592d6d0ab7ea1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201019.150510-12.aar",
          "size": 119560,
          "sha512": "fb02f3a984485d36bf9794dcfcb935245509c8bbc3b886dfa8dccd8f594b5636da6f5965bbf5c5addb0aeeeffd74392e61e68d6bb9a599f82d33a41641969143",
          "sha256": "b811fc1ea38f34d0fbeb9a5b56f13ea6805ee8bf10a410350b23efd3a738d48d",
          "sha1": "0cf10d294e8b8a67376615a1e402229ce70e66fe",
          "md5": "7b09743afa729c93f0f592d6d0ab7ea1"
        }
      ]
    }
  ]
}
