{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22102901-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kdcfeabbpjelbjyaq5ebotoiii"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22102901-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22102901-20221028.172102-1.aar",
          "size": 172945,
          "sha512": "884c3729cf37b6d3bfa20af27d531546161ebdff3115ec2f9b1f63486dde51c5968b77ee41dbade5d32c4a233f3cbd8e5cbbbb534758c40758049b8690b4be5c",
          "sha256": "c1c01aabd1ef02f7ee08b76305aa92e157319796a0ffd77816bec015b91cd9b1",
          "sha1": "1a929ac8a0d7fe733f18e108dfe9a0f2dab3678e",
          "md5": "d3f4011093a3773cc9c3bf8dcfabfb1c"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22102901-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22102901-20221028.172102-1.aar",
          "size": 172945,
          "sha512": "884c3729cf37b6d3bfa20af27d531546161ebdff3115ec2f9b1f63486dde51c5968b77ee41dbade5d32c4a233f3cbd8e5cbbbb534758c40758049b8690b4be5c",
          "sha256": "c1c01aabd1ef02f7ee08b76305aa92e157319796a0ffd77816bec015b91cd9b1",
          "sha1": "1a929ac8a0d7fe733f18e108dfe9a0f2dab3678e",
          "md5": "d3f4011093a3773cc9c3bf8dcfabfb1c"
        }
      ]
    }
  ]
}
