{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "bbfgdyu6yjeehpfntgxkuf724e"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201025.164417-6.aar",
          "size": 37070,
          "sha512": "58c547e1ccdbdb5a1a0dd7307462cdfe300e1d342a6c58ffb6b8a423f713d7d425c5b8399a4348bf019b68b1c8d9318e2ee7b75ec281d476fdd96c68c83af14d",
          "sha256": "6ce8cf683d726e6e282300ea2286fe58785e069e4da647300131822eb8c33382",
          "sha1": "c7b9f392dc820bf77c3bb5c894d66d730636164a",
          "md5": "f62744a788c427f7c962c938be2e7fb6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201025.164417-6.aar",
          "size": 37070,
          "sha512": "58c547e1ccdbdb5a1a0dd7307462cdfe300e1d342a6c58ffb6b8a423f713d7d425c5b8399a4348bf019b68b1c8d9318e2ee7b75ec281d476fdd96c68c83af14d",
          "sha256": "6ce8cf683d726e6e282300ea2286fe58785e069e4da647300131822eb8c33382",
          "sha1": "c7b9f392dc820bf77c3bb5c894d66d730636164a",
          "md5": "f62744a788c427f7c962c938be2e7fb6"
        }
      ]
    }
  ]
}
