{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5uvgrxfo3bhlrh2u2wc7kx5rkq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201021.084530-4.aar",
          "size": 31152,
          "sha512": "8a0d1d4374323bfde63d8c810318059d450745e5d0fd9be73538bcd93ab1c7d60abf9b0a1c1165ea6f9d69a7010250d1812675ea95a160161860ffe942093db7",
          "sha256": "1e432b881feece005812fc53422b23d707bacca95f1da7dbd0dfe9e9cebe9bc1",
          "sha1": "9971cad0ee8dd718397cfbceb0b32dd0e8a8f55f",
          "md5": "0aabb9faa87b22e3af8d57a5bbb6b6e5"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201021.084530-4.aar",
          "size": 31152,
          "sha512": "8a0d1d4374323bfde63d8c810318059d450745e5d0fd9be73538bcd93ab1c7d60abf9b0a1c1165ea6f9d69a7010250d1812675ea95a160161860ffe942093db7",
          "sha256": "1e432b881feece005812fc53422b23d707bacca95f1da7dbd0dfe9e9cebe9bc1",
          "sha1": "9971cad0ee8dd718397cfbceb0b32dd0e8a8f55f",
          "md5": "0aabb9faa87b22e3af8d57a5bbb6b6e5"
        }
      ]
    }
  ]
}
