{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jfo3lf3nhff2xanre4yjx6zjoe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.1.aar",
          "url": "common-0.0.1.aar",
          "size": 19926,
          "sha512": "17fcb8171d6b9d69fa61539a5eba54b1a8d85e31affcab7183ef58a9a37c74b5f06fb653aecf8a56f5e91c4cbe5cc5d996ddbd54ca82051098081a23395815b1",
          "sha256": "65abcaec94a46bff7156879ec65daa8eb2be9965a2e7dec04e66c99cafc3e1c2",
          "sha1": "8471eb1d7bb26c01086e8d69e31bccaf0c6f0bd8",
          "md5": "9c429a23346bcfd5828a9f9baee19998"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.1.aar",
          "url": "common-0.0.1.aar",
          "size": 19926,
          "sha512": "17fcb8171d6b9d69fa61539a5eba54b1a8d85e31affcab7183ef58a9a37c74b5f06fb653aecf8a56f5e91c4cbe5cc5d996ddbd54ca82051098081a23395815b1",
          "sha256": "65abcaec94a46bff7156879ec65daa8eb2be9965a2e7dec04e66c99cafc3e1c2",
          "sha1": "8471eb1d7bb26c01086e8d69e31bccaf0c6f0bd8",
          "md5": "9c429a23346bcfd5828a9f9baee19998"
        }
      ]
    }
  ]
}
