{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012103-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hp2atf7m3bcnjntsg5l7f6h43e"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012103-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012103-20210120.181754-1.aar",
          "size": 44257,
          "sha512": "743307408074ed4356375fef0a21c89df19c02f7c13e2028cf65338046b5132b6b590b2d59aad5b2b6454415bd83a1ba6daf3a1ad50365067034b717ed36ef05",
          "sha256": "d826aa1e238972c604f011ce1d7b3e49270c2b306e96090b6a7ea225998dc4bb",
          "sha1": "6506c18e488db93fc8a556e56e1ad607f91eb845",
          "md5": "acdbd6704c3aba3df33e80f20e6eee02"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012103-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012103-20210120.181754-1.aar",
          "size": 44257,
          "sha512": "743307408074ed4356375fef0a21c89df19c02f7c13e2028cf65338046b5132b6b590b2d59aad5b2b6454415bd83a1ba6daf3a1ad50365067034b717ed36ef05",
          "sha256": "d826aa1e238972c604f011ce1d7b3e49270c2b306e96090b6a7ea225998dc4bb",
          "sha1": "6506c18e488db93fc8a556e56e1ad607f91eb845",
          "md5": "acdbd6704c3aba3df33e80f20e6eee02"
        }
      ]
    }
  ]
}
