{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "gxvmncn4iffsjeqkgxd25jwim4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.1.0-SNAPSHOT.aar",
          "url": "json-dsl-0.1.0-20210105.171026-2.aar",
          "size": 38734,
          "sha512": "1798d46d837e0e5f1954426b2d6ca7bce5fa5f1be33672e14829c98fd835cbb6602ddf577ec4c363dd1c0b748138177ed1d08c8d9c8ba382df85ae7e1bdbe2e1",
          "sha256": "1b5327d55b5acacde13138b6184b7feda88ebea26da566065bda26f05f0bf74d",
          "sha1": "98e5fefd273b6c90d942b6012cb6fc8ab6f347b6",
          "md5": "bbe812bf1dd5193b3edf1832db623c8e"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.1.0-SNAPSHOT.aar",
          "url": "json-dsl-0.1.0-20210105.171026-2.aar",
          "size": 38734,
          "sha512": "1798d46d837e0e5f1954426b2d6ca7bce5fa5f1be33672e14829c98fd835cbb6602ddf577ec4c363dd1c0b748138177ed1d08c8d9c8ba382df85ae7e1bdbe2e1",
          "sha256": "1b5327d55b5acacde13138b6184b7feda88ebea26da566065bda26f05f0bf74d",
          "sha1": "98e5fefd273b6c90d942b6012cb6fc8ab6f347b6",
          "md5": "bbe812bf1dd5193b3edf1832db623c8e"
        }
      ]
    }
  ]
}
