{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "oxbmtsblznaxresns7ultg2jsy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.4.aar",
          "url": "recyclerview-0.9.4.aar",
          "size": 105707,
          "sha512": "035a2cc8d2a8e84ff0255470a4cb280ad3c6b0212de39c667b8e7a95a0050c241bb565004a2972c4a8535fb2f65e3a7e3630aef0a143e0127b446d1a8093a0f7",
          "sha256": "39573077dab3a7f17e2c6b36def61ae9ffdfd4a8041db4d1a1c9e4a58d9d4709",
          "sha1": "5315d2dc582ee21eefb7b99c684d0f4759e4edf2",
          "md5": "4d37f6995cdbe16852f23569946a7cf5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.4.aar",
          "url": "recyclerview-0.9.4.aar",
          "size": 105707,
          "sha512": "035a2cc8d2a8e84ff0255470a4cb280ad3c6b0212de39c667b8e7a95a0050c241bb565004a2972c4a8535fb2f65e3a7e3630aef0a143e0127b446d1a8093a0f7",
          "sha256": "39573077dab3a7f17e2c6b36def61ae9ffdfd4a8041db4d1a1c9e4a58d9d4709",
          "sha1": "5315d2dc582ee21eefb7b99c684d0f4759e4edf2",
          "md5": "4d37f6995cdbe16852f23569946a7cf5"
        }
      ]
    }
  ]
}
