{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22070421-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cjqsv3cz6rbd5pxqzryomgmium"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22070421-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22070421-20220704.140427-1.aar",
          "size": 156989,
          "sha512": "bf2955d05b5c370e67074c144c2f9c62b9432dcef113acfde07f6f81e4d97708b02592b895b8236355594bb201bf6adb8bc20e2abfac428e9806929a11a195f1",
          "sha256": "f20d5a71d35d19ce151ae9336e2d1ce55b379506e3126afd038a01fea48ada89",
          "sha1": "82af9d84749436453040ed2969954a763007cb71",
          "md5": "c45a4028133c7c689934569f14f430cb"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22040815-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22070421-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22070421-20220704.140427-1.aar",
          "size": 156989,
          "sha512": "bf2955d05b5c370e67074c144c2f9c62b9432dcef113acfde07f6f81e4d97708b02592b895b8236355594bb201bf6adb8bc20e2abfac428e9806929a11a195f1",
          "sha256": "f20d5a71d35d19ce151ae9336e2d1ce55b379506e3126afd038a01fea48ada89",
          "sha1": "82af9d84749436453040ed2969954a763007cb71",
          "md5": "c45a4028133c7c689934569f14f430cb"
        }
      ]
    }
  ]
}
