{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.21110716-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tgi2n5dewbb6vh3g7t4rwqfgcq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110716-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110716-20211107.081213-1.aar",
          "size": 119094,
          "sha512": "016fec202b86aa6a479f2e1499f1e3ae40007ac4b6a2c501410e2ba33fc6991535743f88113a0c562bc32c65bfb862a4d4c6270e88a724122a5ef3f4b393d008",
          "sha256": "7e70c689c36159ae556fe4a58417477d249eca44353db390dc9c7fa8e59e8cdd",
          "sha1": "98b83c6cd72a3e72442728db821724d9da4c6b0b",
          "md5": "266148a33ecd9cea9d90be0e885309ed"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110716-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110716-20211107.081213-1.aar",
          "size": 119094,
          "sha512": "016fec202b86aa6a479f2e1499f1e3ae40007ac4b6a2c501410e2ba33fc6991535743f88113a0c562bc32c65bfb862a4d4c6270e88a724122a5ef3f4b393d008",
          "sha256": "7e70c689c36159ae556fe4a58417477d249eca44353db390dc9c7fa8e59e8cdd",
          "sha1": "98b83c6cd72a3e72442728db821724d9da4c6b0b",
          "md5": "266148a33ecd9cea9d90be0e885309ed"
        }
      ]
    }
  ]
}
