{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "eyhzv2izhneunpofyx4uqrx7oa"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.1.0-SNAPSHOT.aar",
          "url": "json-dsl-0.1.0-20210105.165516-1.aar",
          "size": 38691,
          "sha512": "63152ea56757e93f608248b94cf968b63b98c8d384ac414c31fb2c7c93c5117b07a0565a6c0c397e8f4f810e4fedf20c5de59427bf921ce9206f4c10e5de8ffb",
          "sha256": "baa5167bf0c7e2b14431bb29764dcfc4d1d014ba351461efbc24c4d16c933821",
          "sha1": "3face2f58f657baf71f6c5d0af157e1ddf1ce6aa",
          "md5": "cf8d75b81be6c0f740c29bcbbb10f41b"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.1.0-SNAPSHOT.aar",
          "url": "json-dsl-0.1.0-20210105.165516-1.aar",
          "size": 38691,
          "sha512": "63152ea56757e93f608248b94cf968b63b98c8d384ac414c31fb2c7c93c5117b07a0565a6c0c397e8f4f810e4fedf20c5de59427bf921ce9206f4c10e5de8ffb",
          "sha256": "baa5167bf0c7e2b14431bb29764dcfc4d1d014ba351461efbc24c4d16c933821",
          "sha1": "3face2f58f657baf71f6c5d0af157e1ddf1ce6aa",
          "md5": "cf8d75b81be6c0f740c29bcbbb10f41b"
        }
      ]
    }
  ]
}
