{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "kanban",
    "version": "0.0.1.22012702-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "4rl3ciyotfhjti4wz63hljj2sm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kanban-0.0.1.22012702-SNAPSHOT.aar",
          "url": "kanban-0.0.1.22012702-20220217.111128-2.aar",
          "size": 44897,
          "sha512": "d2912492c2061c4e0ed9c342707a061ad5d8580f18568ddd31cbb0ff64a9d76e5b016c2f26ba25883aae04786d0e64126ac04ad8511d9d8954d8b5e06349fe06",
          "sha256": "9692dd867d5740527046afb2c5ef5fa93dd78b82f21664ce6764ed7b52af898e",
          "sha1": "be06c23bdd1d474a52f3bf75b7b6cf07d4735ead",
          "md5": "f233147ce72abc39648d6b36abc9fd12"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kanban-0.0.1.22012702-SNAPSHOT.aar",
          "url": "kanban-0.0.1.22012702-20220217.111128-2.aar",
          "size": 44897,
          "sha512": "d2912492c2061c4e0ed9c342707a061ad5d8580f18568ddd31cbb0ff64a9d76e5b016c2f26ba25883aae04786d0e64126ac04ad8511d9d8954d8b5e06349fe06",
          "sha256": "9692dd867d5740527046afb2c5ef5fa93dd78b82f21664ce6764ed7b52af898e",
          "sha1": "be06c23bdd1d474a52f3bf75b7b6cf07d4735ead",
          "md5": "f233147ce72abc39648d6b36abc9fd12"
        }
      ]
    }
  ]
}
