{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22070501-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "clb726pqdrbfnmo57uqopac2g4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22070501-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22070501-20220704.170227-1.aar",
          "size": 157149,
          "sha512": "a501873e3632b1120d228a1e406a6fc4871faf2d9f63352275b002475c1abcf51d821c246e31e4a04044d966282ff2301c86a0b5f30602b57446e92435e66f3b",
          "sha256": "d652f6d2682fafce24e819e52fdf3fc051ff3e7ace1afb59436a3208ee1248d4",
          "sha1": "0cb1e3767d411fb81d6786ce3cd2212834db3b10",
          "md5": "ca050865b65975f40e4c1fa1d17b4077"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22040815-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22070501-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22070501-20220704.170227-1.aar",
          "size": 157149,
          "sha512": "a501873e3632b1120d228a1e406a6fc4871faf2d9f63352275b002475c1abcf51d821c246e31e4a04044d966282ff2301c86a0b5f30602b57446e92435e66f3b",
          "sha256": "d652f6d2682fafce24e819e52fdf3fc051ff3e7ace1afb59436a3208ee1248d4",
          "sha1": "0cb1e3767d411fb81d6786ce3cd2212834db3b10",
          "md5": "ca050865b65975f40e4c1fa1d17b4077"
        }
      ]
    }
  ]
}
