{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.21030519-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "natfb6q7rfbnnamadclnnoyjga"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.21030519-SNAPSHOT.aar",
          "url": "common-0.0.9.21030519-20210305.112204-1.aar",
          "size": 48756,
          "sha512": "dc08710366bb848888e111e99fda6a644d8c408a319b150613a708fba0f2affec4c7331a486cbd6c0e8b599eb1bfba89eb2415e4448a0b3ded9807b0325b65c2",
          "sha256": "d86526028c5d9a51cb5a4e10acdc0035faf1a3f633fb48e9e336697cdf27d231",
          "sha1": "f44007b84e8cacd34808af16d951d0416bbbdc2a",
          "md5": "7d9eddcf8a6e5bf19212bb5bf15e26cf"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.21030519-SNAPSHOT.aar",
          "url": "common-0.0.9.21030519-20210305.112204-1.aar",
          "size": 48756,
          "sha512": "dc08710366bb848888e111e99fda6a644d8c408a319b150613a708fba0f2affec4c7331a486cbd6c0e8b599eb1bfba89eb2415e4448a0b3ded9807b0325b65c2",
          "sha256": "d86526028c5d9a51cb5a4e10acdc0035faf1a3f633fb48e9e336697cdf27d231",
          "sha1": "f44007b84e8cacd34808af16d951d0416bbbdc2a",
          "md5": "7d9eddcf8a6e5bf19212bb5bf15e26cf"
        }
      ]
    }
  ]
}
