{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012003-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "qsgs2pb25rh3lperysl6gm5oie"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012003-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012003-20210119.183937-1.aar",
          "size": 42219,
          "sha512": "a6a08cbc9dbc8be0af5069ac450f5568fc61235bacf8ff476570682d6bb4e1f4682eb09c4afa9442f8ee85c3cfb51d5fad31aa49ae09ca53e6772873297baf10",
          "sha256": "8674eaeb79aaaf5f5440542fdb3919fddf1c1f3ff96074ed825b68a6bd71e6a2",
          "sha1": "94711cf5fcdb295508fa08f87de5c52896353b45",
          "md5": "39bd0d312512832029f1ff1f2b736d56"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012003-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012003-20210119.183937-1.aar",
          "size": 42219,
          "sha512": "a6a08cbc9dbc8be0af5069ac450f5568fc61235bacf8ff476570682d6bb4e1f4682eb09c4afa9442f8ee85c3cfb51d5fad31aa49ae09ca53e6772873297baf10",
          "sha256": "8674eaeb79aaaf5f5440542fdb3919fddf1c1f3ff96074ed825b68a6bd71e6a2",
          "sha1": "94711cf5fcdb295508fa08f87de5c52896353b45",
          "md5": "39bd0d312512832029f1ff1f2b736d56"
        }
      ]
    }
  ]
}
