{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "irzu6majobd7zlozvmsqkzgx6y"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201022.182835-29.aar",
          "size": 123405,
          "sha512": "25b53ce6006d89f6827ceeadc3175297d987d87e6fff682e612690de809fcd4ad835a7208c2c3e1aa940e7e269023341787208cd49e4498afee47b513d892558",
          "sha256": "f36b5763ad301311d4320d4edcb2b95cc7826f82cdfdef00acb36d9ad54c75f2",
          "sha1": "c7f56dd401a2a80e42fa6304900ac7a115e259ae",
          "md5": "82e13636dcf7e9db40c422e7f820e46b"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201022.182835-29.aar",
          "size": 123405,
          "sha512": "25b53ce6006d89f6827ceeadc3175297d987d87e6fff682e612690de809fcd4ad835a7208c2c3e1aa940e7e269023341787208cd49e4498afee47b513d892558",
          "sha256": "f36b5763ad301311d4320d4edcb2b95cc7826f82cdfdef00acb36d9ad54c75f2",
          "sha1": "c7f56dd401a2a80e42fa6304900ac7a115e259ae",
          "md5": "82e13636dcf7e9db40c422e7f820e46b"
        }
      ]
    }
  ]
}
