{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.22042423-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yopfuwna5jfm5nbeakfotgud6u"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.22042423-SNAPSHOT.aar",
          "url": "common-0.0.9.22042423-20220424.153646-1.aar",
          "size": 51074,
          "sha512": "20239bf1effbee525e94a3d774ddd830965064607356dfa46a5fce576938220747ef42712594b9457c5a1e35abdde7229c5736e13d5ab976adcb598688affd90",
          "sha256": "82f0436f0136eb4f552a3a5d6a87beac9a4dbcc9b5968d62d60ed6c670119993",
          "sha1": "a06794a3342d6d24318d773f9e8705aba1aee900",
          "md5": "b58886fedbf306f2b8d81d2f5df231b1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.22042423-SNAPSHOT.aar",
          "url": "common-0.0.9.22042423-20220424.153646-1.aar",
          "size": 51074,
          "sha512": "20239bf1effbee525e94a3d774ddd830965064607356dfa46a5fce576938220747ef42712594b9457c5a1e35abdde7229c5736e13d5ab976adcb598688affd90",
          "sha256": "82f0436f0136eb4f552a3a5d6a87beac9a4dbcc9b5968d62d60ed6c670119993",
          "sha1": "a06794a3342d6d24318d773f9e8705aba1aee900",
          "md5": "b58886fedbf306f2b8d81d2f5df231b1"
        }
      ]
    }
  ]
}
