{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.23022217-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ssoqffcrarb23ooowzgdaf5g54"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022217-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022217-20230222.095620-1.aar",
          "size": 182988,
          "sha512": "af3e650e19dd002a4562d2e736ab707088de05e724609835a7ed54180cc7ab55f8e86bad51a9273d17be8d80290eb01de7bce5cc252d7cc4156bd5911b8ffadc",
          "sha256": "976ca0dfc95b11bde1cfa18fa447adaa6944dc1034679b8a25589d7d1394a69d",
          "sha1": "6c198bc60df862910c18af839d98b4ccf422f9d6",
          "md5": "6e6f019eed7d756b5072553ef4545c89"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022217-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022217-20230222.095620-1.aar",
          "size": 182988,
          "sha512": "af3e650e19dd002a4562d2e736ab707088de05e724609835a7ed54180cc7ab55f8e86bad51a9273d17be8d80290eb01de7bce5cc252d7cc4156bd5911b8ffadc",
          "sha256": "976ca0dfc95b11bde1cfa18fa447adaa6944dc1034679b8a25589d7d1394a69d",
          "sha1": "6c198bc60df862910c18af839d98b4ccf422f9d6",
          "md5": "6e6f019eed7d756b5072553ef4545c89"
        }
      ]
    }
  ]
}
