{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.220050801-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5fdxnspxmvh35cgmufvoc6rm5i"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.220050801-SNAPSHOT.aar",
          "url": "common-0.0.9.220050801-20220507.170618-1.aar",
          "size": 52604,
          "sha512": "ad9ca3072c3ccf445d5b49a92517b76e2d505acded30e9453a58b4517af33fa1ee913be6117f743cde42321e5f74a82b45779e08fcc12b564d3ab57eb07630d4",
          "sha256": "881a2f3a14903a688185b935fdff6c766c6809b9d31e2ff00e46bc8841026ed0",
          "sha1": "eb77f82bb1bbc8cd7a649a61ca2b327343818771",
          "md5": "06d4609ca6abbf7eb1c0058b17849054"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.220050801-SNAPSHOT.aar",
          "url": "common-0.0.9.220050801-20220507.170618-1.aar",
          "size": 52604,
          "sha512": "ad9ca3072c3ccf445d5b49a92517b76e2d505acded30e9453a58b4517af33fa1ee913be6117f743cde42321e5f74a82b45779e08fcc12b564d3ab57eb07630d4",
          "sha256": "881a2f3a14903a688185b935fdff6c766c6809b9d31e2ff00e46bc8841026ed0",
          "sha1": "eb77f82bb1bbc8cd7a649a61ca2b327343818771",
          "md5": "06d4609ca6abbf7eb1c0058b17849054"
        }
      ]
    }
  ]
}
