{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21082305-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vzwlgnpl3vgf5b2vbuhxdqpaxu"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21082305-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21082305-20210822.185520-1.aar",
          "size": 137452,
          "sha512": "e3864ed399696716a6627c4b7107867fdde0b559c3cfd3a0eefb604fc74fe2bca2e8e9690b5721ba6c4dcbe23ba672ae683ba335e430c089d771e3a1704d74af",
          "sha256": "722a73a387871afcffc18833cff3208483c592ac5da2f3c03f72b0c96139d714",
          "sha1": "68aaa82b30e76ae91b426cb04cdaf71a4fb8c7c2",
          "md5": "7f079c1fad19b3be9b9b3a9849d9baaa"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21082305-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21082305-20210822.185520-1.aar",
          "size": 137452,
          "sha512": "e3864ed399696716a6627c4b7107867fdde0b559c3cfd3a0eefb604fc74fe2bca2e8e9690b5721ba6c4dcbe23ba672ae683ba335e430c089d771e3a1704d74af",
          "sha256": "722a73a387871afcffc18833cff3208483c592ac5da2f3c03f72b0c96139d714",
          "sha1": "68aaa82b30e76ae91b426cb04cdaf71a4fb8c7c2",
          "md5": "7f079c1fad19b3be9b9b3a9849d9baaa"
        }
      ]
    }
  ]
}
