{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012821-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "l54234u3pjcahgrcf4mryowv2u"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012821-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012821-20210128.133622-1.aar",
          "size": 48108,
          "sha512": "b6552a6472f1a9105b918504e701bb55521a2e8a94631297a04ff05587321446aba112d69f7eb0b36d9e8cd8957e08cfa68958b08428332f80c2b379c3d8a13a",
          "sha256": "bf19a2cca6e649d123e02ee238db9ee0366894754c10d5f5d3be5b6bc18dcf67",
          "sha1": "e3dbe18f034271a8d532cca98e37152909ec6b6c",
          "md5": "a2f9ad4edc707b4da5d7f1565cc45b20"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012821-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012821-20210128.133622-1.aar",
          "size": 48108,
          "sha512": "b6552a6472f1a9105b918504e701bb55521a2e8a94631297a04ff05587321446aba112d69f7eb0b36d9e8cd8957e08cfa68958b08428332f80c2b379c3d8a13a",
          "sha256": "bf19a2cca6e649d123e02ee238db9ee0366894754c10d5f5d3be5b6bc18dcf67",
          "sha1": "e3dbe18f034271a8d532cca98e37152909ec6b6c",
          "md5": "a2f9ad4edc707b4da5d7f1565cc45b20"
        }
      ]
    }
  ]
}
