{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "lumll2tnvbcmph2nxah3yxe56y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.3.aar",
          "url": "common-0.0.3.aar",
          "size": 20665,
          "sha512": "29236d249dedc4d47d82afbb4679c1fb1ca9678db50bfabbd4e06081b0d8834de60875d7958411ebc092d5c90400c464edf0bb0b9a5003061fca9be587f42f47",
          "sha256": "a4f6b691a6db6cde9e16918aa3d7bdc7276cc471db98f00b880d2400adc4b239",
          "sha1": "f5f1321e2c760f641c82b64bfde8ae00aff595b7",
          "md5": "0f4682c121d5f56a34c1a1040072cc81"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.3.aar",
          "url": "common-0.0.3.aar",
          "size": 20665,
          "sha512": "29236d249dedc4d47d82afbb4679c1fb1ca9678db50bfabbd4e06081b0d8834de60875d7958411ebc092d5c90400c464edf0bb0b9a5003061fca9be587f42f47",
          "sha256": "a4f6b691a6db6cde9e16918aa3d7bdc7276cc471db98f00b880d2400adc4b239",
          "sha1": "f5f1321e2c760f641c82b64bfde8ae00aff595b7",
          "md5": "0f4682c121d5f56a34c1a1040072cc81"
        }
      ]
    }
  ]
}
