{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "x6kjm5xgvrbhfh7dglmflssn3q"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201101.150305-2.aar",
          "size": 132606,
          "sha512": "07c9045683382e95e0f337396dce82aa97a1d56984c62fa6624c5929bc3352c8c518f83f3a19d69e12adbad2d3fe334e3c68a9933187352ccfb65899f5020a88",
          "sha256": "00e931903648d84a943d5786ddd099b2e6d09f800b1f80e8d9451b5ad22f3572",
          "sha1": "c7222ec62e26c4081730c53ebfa48c4e1b8d8a8e",
          "md5": "9ee13ac791c3967e4e1759e2b4219b88"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201101.150305-2.aar",
          "size": 132606,
          "sha512": "07c9045683382e95e0f337396dce82aa97a1d56984c62fa6624c5929bc3352c8c518f83f3a19d69e12adbad2d3fe334e3c68a9933187352ccfb65899f5020a88",
          "sha256": "00e931903648d84a943d5786ddd099b2e6d09f800b1f80e8d9451b5ad22f3572",
          "sha1": "c7222ec62e26c4081730c53ebfa48c4e1b8d8a8e",
          "md5": "9ee13ac791c3967e4e1759e2b4219b88"
        }
      ]
    }
  ]
}
