{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "a2uk36pfsvfypgspuop7uwk5gm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.1.aar",
          "url": "recyclerview-0.9.1.aar",
          "size": 103619,
          "sha512": "a191517cc68a31f48e8f7ef113b7b402a2bc0b8f82a6009a29331e4c4a80932dc9df076c4e09b6449f986672d34cc9f492158888299ae7ffff75fdb981e00394",
          "sha256": "7b760f1fdd5b093d9b51b3d52e3cfef8fa69479f9d385b86ed08f7484159a6c8",
          "sha1": "d24054c0b461fa20319af7840681eab5354f879d",
          "md5": "832a70f5372963754744415eb52f357d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.1.aar",
          "url": "recyclerview-0.9.1.aar",
          "size": 103619,
          "sha512": "a191517cc68a31f48e8f7ef113b7b402a2bc0b8f82a6009a29331e4c4a80932dc9df076c4e09b6449f986672d34cc9f492158888299ae7ffff75fdb981e00394",
          "sha256": "7b760f1fdd5b093d9b51b3d52e3cfef8fa69479f9d385b86ed08f7484159a6c8",
          "sha1": "d24054c0b461fa20319af7840681eab5354f879d",
          "md5": "832a70f5372963754744415eb52f357d"
        }
      ]
    }
  ]
}
