{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22122322-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rjjrysz6unf6pms6xndgjux7am"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22122322-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22122322-20221223.140310-1.aar",
          "size": 176116,
          "sha512": "a6db847b2a8c396fcae4d72ac7b11b1f6f37ee0f48dfc1beda5546d4ab69fd117efccc60752e2c3632c9b4e988edb57e045f95dd5294c8ac2cf5c7c75339bb81",
          "sha256": "67f54c6da5a068749444afccf94f4e91bf9e533e780c563e5e3626a975d23fa8",
          "sha1": "28de86579d4f11ed72f618ffb8e568a0ebe95680",
          "md5": "9d53dbd23491c268e013735221e2deb8"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22122322-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22122322-20221223.140310-1.aar",
          "size": 176116,
          "sha512": "a6db847b2a8c396fcae4d72ac7b11b1f6f37ee0f48dfc1beda5546d4ab69fd117efccc60752e2c3632c9b4e988edb57e045f95dd5294c8ac2cf5c7c75339bb81",
          "sha256": "67f54c6da5a068749444afccf94f4e91bf9e533e780c563e5e3626a975d23fa8",
          "sha1": "28de86579d4f11ed72f618ffb8e568a0ebe95680",
          "md5": "9d53dbd23491c268e013735221e2deb8"
        }
      ]
    }
  ]
}
