{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "46yuhxjnpbhdde23hslo5atnum"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.103358-4.aar",
          "size": 129778,
          "sha512": "fd47644bc7afd7057da9d11931887d0403be7fa3d6ecd2bead04a8ba0bcfe0a70b15fd630a372addcbb5276e46dd7e9467591ffb0694abfd92a2e7825e33a0bb",
          "sha256": "0fd88bd6ae428fd0a3c98d941e565eeaedf5f9deebe536b471f3f7ff2330299d",
          "sha1": "7a3b34d7ff72b636ea244ac733bbc05368741b6b",
          "md5": "4d1ad8596d8e04d70dab3eacdb2ec2a9"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.103358-4.aar",
          "size": 129778,
          "sha512": "fd47644bc7afd7057da9d11931887d0403be7fa3d6ecd2bead04a8ba0bcfe0a70b15fd630a372addcbb5276e46dd7e9467591ffb0694abfd92a2e7825e33a0bb",
          "sha256": "0fd88bd6ae428fd0a3c98d941e565eeaedf5f9deebe536b471f3f7ff2330299d",
          "sha1": "7a3b34d7ff72b636ea244ac733bbc05368741b6b",
          "md5": "4d1ad8596d8e04d70dab3eacdb2ec2a9"
        }
      ]
    }
  ]
}
