{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.21101500-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "i2qj6jymuffgdectzveev3n3zy"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21101500-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21101500-20211107.073236-1.aar",
          "size": 118308,
          "sha512": "2c6edd58c748b2a84c286e5e443cb91d0fa9bf01ac866363243241d55e5dceec6b23241f65d8566ba9169b52d57611caab64a66bc24d02e4da9533dd7e6da144",
          "sha256": "5b50a3737e196bc771003179c7e8cea2b2a61f5e9a1f7f423152d24075edd4a8",
          "sha1": "62430668c740ee6482c9ddd7d781078b257e3efb",
          "md5": "a2c2ca603c259d20dffb5fb7e6cd59af"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21101500-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21101500-20211107.073236-1.aar",
          "size": 118308,
          "sha512": "2c6edd58c748b2a84c286e5e443cb91d0fa9bf01ac866363243241d55e5dceec6b23241f65d8566ba9169b52d57611caab64a66bc24d02e4da9533dd7e6da144",
          "sha256": "5b50a3737e196bc771003179c7e8cea2b2a61f5e9a1f7f423152d24075edd4a8",
          "sha1": "62430668c740ee6482c9ddd7d781078b257e3efb",
          "md5": "a2c2ca603c259d20dffb5fb7e6cd59af"
        }
      ]
    }
  ]
}
