{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21042218-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "z2abboqyr5ho5cy5ytmonwcl3i"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21042218-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21042218-20210422.104345-1.aar",
          "size": 48473,
          "sha512": "36705eae0c6c7a2b73e39cd9cd6b7a2050645d5299353c911c564fc9335b36d46be2d9ea0d9cc890714a11a9d42203b2a887206d4661847d57ab3e5ab4f104ce",
          "sha256": "2b1d61349ae8b6b01ce164f534f6e8741e15e8bca8aa58335c64d49f44f3fe59",
          "sha1": "0537cf36d9b388ac819762749e63ea74475b3046",
          "md5": "4f349e74933b835100aa9d8b6bb96078"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21042218-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21042218-20210422.104345-1.aar",
          "size": 48473,
          "sha512": "36705eae0c6c7a2b73e39cd9cd6b7a2050645d5299353c911c564fc9335b36d46be2d9ea0d9cc890714a11a9d42203b2a887206d4661847d57ab3e5ab4f104ce",
          "sha256": "2b1d61349ae8b6b01ce164f534f6e8741e15e8bca8aa58335c64d49f44f3fe59",
          "sha1": "0537cf36d9b388ac819762749e63ea74475b3046",
          "md5": "4f349e74933b835100aa9d8b6bb96078"
        }
      ]
    }
  ]
}
