{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21020601-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pphmkr5fzjebnegfkqvokz2b4i"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020601-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020601-20210205.180407-2.aar",
          "size": 135393,
          "sha512": "6b5ecbaa3512793d6ffda1d435fc313e751e363105dea0e3a13578dfa8eea1e0f200c0f4fd7be91daf6d4e4b43c386e65aa99aa4b34f558189fc9762efab519c",
          "sha256": "d81dee04e7d13be8f4844f38287db83158410bccfba4bceb9357fee7157e047a",
          "sha1": "f85443459695f5777e99a5c24de22b3df02066f0",
          "md5": "515578e430a48fba796e0b099aa3a330"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020601-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020601-20210205.180407-2.aar",
          "size": 135393,
          "sha512": "6b5ecbaa3512793d6ffda1d435fc313e751e363105dea0e3a13578dfa8eea1e0f200c0f4fd7be91daf6d4e4b43c386e65aa99aa4b34f558189fc9762efab519c",
          "sha256": "d81dee04e7d13be8f4844f38287db83158410bccfba4bceb9357fee7157e047a",
          "sha1": "f85443459695f5777e99a5c24de22b3df02066f0",
          "md5": "515578e430a48fba796e0b099aa3a330"
        }
      ]
    }
  ]
}
