{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22012401-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "aeq3vdwdrneolneeua7m36ws5i"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012401-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012401-20220123.172322-1.aar",
          "size": 119035,
          "sha512": "a8a0af32327d02115e881d3e2508d11a8b2ed44aae499cb77c5519e3a7e06e4d5e6b5c8fadb733d9f2fbc05ec78b94df8f53678f59fa2c054c9cbfc7f219cff7",
          "sha256": "5a8d6a9a19616d695510ae383d7437699a9decc579c66bebd98d12b6601e5621",
          "sha1": "5b79eb169269bc37e6a8c73169faaa55974ecffe",
          "md5": "a044285647aaf19ebd4e9f597e51d2ce"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012401-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012401-20220123.172322-1.aar",
          "size": 119035,
          "sha512": "a8a0af32327d02115e881d3e2508d11a8b2ed44aae499cb77c5519e3a7e06e4d5e6b5c8fadb733d9f2fbc05ec78b94df8f53678f59fa2c054c9cbfc7f219cff7",
          "sha256": "5a8d6a9a19616d695510ae383d7437699a9decc579c66bebd98d12b6601e5621",
          "sha1": "5b79eb169269bc37e6a8c73169faaa55974ecffe",
          "md5": "a044285647aaf19ebd4e9f597e51d2ce"
        }
      ]
    }
  ]
}
