{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "kanban",
    "version": "0.0.1.21042300-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7dxlxxbw4jhtzkxb2lbduuuzi4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kanban-0.0.1.21042300-SNAPSHOT.aar",
          "url": "kanban-0.0.1.21042300-20210422.164639-1.aar",
          "size": 47151,
          "sha512": "c052a38f464026ad0d189ea5aa56a743c5d8ed8fdd620af92e0d4c181f4e3b352af9e71353b691df4ce7651d7b919216bbd5d729bfef48cae430487362a59fde",
          "sha256": "4859c174ecfdd2b760acd0adc924dd2e6629525badbd5da34ad70ca74f5aef87",
          "sha1": "1cdfdf6336d4ce1c98a7c65f8ab34d270bc73b57",
          "md5": "8e312bccf93482a93409b86c3ef7be67"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kanban-0.0.1.21042300-SNAPSHOT.aar",
          "url": "kanban-0.0.1.21042300-20210422.164639-1.aar",
          "size": 47151,
          "sha512": "c052a38f464026ad0d189ea5aa56a743c5d8ed8fdd620af92e0d4c181f4e3b352af9e71353b691df4ce7651d7b919216bbd5d729bfef48cae430487362a59fde",
          "sha256": "4859c174ecfdd2b760acd0adc924dd2e6629525badbd5da34ad70ca74f5aef87",
          "sha1": "1cdfdf6336d4ce1c98a7c65f8ab34d270bc73b57",
          "md5": "8e312bccf93482a93409b86c3ef7be67"
        }
      ]
    }
  ]
}
