{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21020601-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mslxc5ygmrbh5cuddyi3q6rwae"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020601-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020601-20210205.180038-1.aar",
          "size": 135108,
          "sha512": "4825bb77e1a39f602de1eba9cf2f594cc7fc2e193a687895da5109bcd3c3bae77ec06f17c013a2475634f072f4c755e58c6f0fb9bdbfc8f038d847846ed24709",
          "sha256": "98cf7d185dd0b519c3be2cc4d5413e09af5b2ec07ac10ba79500b06d3af12b0a",
          "sha1": "ead409f335c175d88b108310ba5358fc606c165b",
          "md5": "5f78a7f7270147060465bf9325905544"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020601-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020601-20210205.180038-1.aar",
          "size": 135108,
          "sha512": "4825bb77e1a39f602de1eba9cf2f594cc7fc2e193a687895da5109bcd3c3bae77ec06f17c013a2475634f072f4c755e58c6f0fb9bdbfc8f038d847846ed24709",
          "sha256": "98cf7d185dd0b519c3be2cc4d5413e09af5b2ec07ac10ba79500b06d3af12b0a",
          "sha1": "ead409f335c175d88b108310ba5358fc606c165b",
          "md5": "5f78a7f7270147060465bf9325905544"
        }
      ]
    }
  ]
}
