{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2207050101-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "wgrjuxgb2neppipjplf6yhevvi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2207050101-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2207050101-20220709.160126-2.aar",
          "size": 158296,
          "sha512": "32bfb19e1b0a5474cb19a7e0006be91433d9506681b4779ba7f776c6f6d80dc3dbe1acf92623ffa50222adcd79d4ed66f3d9eb512d7903f649af2093b47f8b14",
          "sha256": "6d3b6731cbcfc111a29604fee66ee8946849e812aad732580f4c97b6f5c7483a",
          "sha1": "49ecd234225036b95135a20682163242f9363434",
          "md5": "39a1babd193dc9e4f668cf8787316f37"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22040815-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2207050101-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2207050101-20220709.160126-2.aar",
          "size": 158296,
          "sha512": "32bfb19e1b0a5474cb19a7e0006be91433d9506681b4779ba7f776c6f6d80dc3dbe1acf92623ffa50222adcd79d4ed66f3d9eb512d7903f649af2093b47f8b14",
          "sha256": "6d3b6731cbcfc111a29604fee66ee8946849e812aad732580f4c97b6f5c7483a",
          "sha1": "49ecd234225036b95135a20682163242f9363434",
          "md5": "39a1babd193dc9e4f668cf8787316f37"
        }
      ]
    }
  ]
}
