{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22111022-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cupynlkpzfgjhmhffkngqjjcdm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22111022-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22111022-20221110.144003-1.aar",
          "size": 173019,
          "sha512": "e41faf9f9ef0ef16966895f4aee2d7ee3b8aa01a86486557675381fb8d54ffb847cf371f9fee2755bcbe77e2a2540afeaa42538eca3b07344ee79c16425b33b4",
          "sha256": "5153b49ea90df2bb0c06fa5274dfee6d4d1736bd5c982459981a1ddfe76ffa73",
          "sha1": "a82b2ae7a19317cef9cb50d9c9a663e857127b47",
          "md5": "32a0da80f378d4d4bf6ea05bed80eba1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22111022-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22111022-20221110.144003-1.aar",
          "size": 173019,
          "sha512": "e41faf9f9ef0ef16966895f4aee2d7ee3b8aa01a86486557675381fb8d54ffb847cf371f9fee2755bcbe77e2a2540afeaa42538eca3b07344ee79c16425b33b4",
          "sha256": "5153b49ea90df2bb0c06fa5274dfee6d4d1736bd5c982459981a1ddfe76ffa73",
          "sha1": "a82b2ae7a19317cef9cb50d9c9a663e857127b47",
          "md5": "32a0da80f378d4d4bf6ea05bed80eba1"
        }
      ]
    }
  ]
}
