{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "widgets",
    "version": "0.0.1.22092821-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "shrt55k4x5hltmulbvpw3jfrjm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.22092821-SNAPSHOT.aar",
          "url": "widgets-0.0.1.22092821-20220928.134448-1.aar",
          "size": 31559,
          "sha512": "4c56d6593fb7e87434cc0833e293bfbb8c10161a6813dd802163fc8839729000395477ae5873abd5558693ed20e4a42fe9d6349087d8ce9f3eed724ccfa9563b",
          "sha256": "6f4e954aa42eefeda28eaf86f92394dcbc7b721c9a9956671d131527a378469c",
          "sha1": "003ab32989ed73c1b09f9c2ee0371f367b62a945",
          "md5": "cf6f54cbe14ce320100e9ce12c9f269e"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.22092821-SNAPSHOT.aar",
          "url": "widgets-0.0.1.22092821-20220928.134448-1.aar",
          "size": 31559,
          "sha512": "4c56d6593fb7e87434cc0833e293bfbb8c10161a6813dd802163fc8839729000395477ae5873abd5558693ed20e4a42fe9d6349087d8ce9f3eed724ccfa9563b",
          "sha256": "6f4e954aa42eefeda28eaf86f92394dcbc7b721c9a9956671d131527a378469c",
          "sha1": "003ab32989ed73c1b09f9c2ee0371f367b62a945",
          "md5": "cf6f54cbe14ce320100e9ce12c9f269e"
        }
      ]
    }
  ]
}
