{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5hd55uvkw5coxbkdrsudd7ufwm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.6-SNAPSHOT.aar",
          "url": "common-0.0.6-20201127.160255-5.aar",
          "size": 49170,
          "sha512": "f075b29e6e046097706524b57b6c842c32b193409c0d5c796bda2822bab4a56f143e64080a3c2f044e5bef23efb673b3ed343a6b88340b4f30f4f60695dd6a49",
          "sha256": "3010c33dd29ba200dd7daf4ff0a0dcec41db476e5e2f3931f87d16341b0eba99",
          "sha1": "035ff7cc8bdf32325eb883a11f7a5d8fd19562a0",
          "md5": "b254e925c0105a0a82b6e6872af48a5d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.6-SNAPSHOT.aar",
          "url": "common-0.0.6-20201127.160255-5.aar",
          "size": 49170,
          "sha512": "f075b29e6e046097706524b57b6c842c32b193409c0d5c796bda2822bab4a56f143e64080a3c2f044e5bef23efb673b3ed343a6b88340b4f30f4f60695dd6a49",
          "sha256": "3010c33dd29ba200dd7daf4ff0a0dcec41db476e5e2f3931f87d16341b0eba99",
          "sha1": "035ff7cc8bdf32325eb883a11f7a5d8fd19562a0",
          "md5": "b254e925c0105a0a82b6e6872af48a5d"
        }
      ]
    }
  ]
}
