{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "kanban",
    "version": "0.0.1.21110918-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "bgtd5mcr6jeqfjo5hf27y3j5iq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kanban-0.0.1.21110918-SNAPSHOT.aar",
          "url": "kanban-0.0.1.21110918-20220106.164511-3.aar",
          "size": 44476,
          "sha512": "f46001777ad3339b09df85089fc16406764e576b38c406b4bd535d330ba30858486b27591d5ca17ae4f941ae35e4e7a57fb272ea273264f0137b4cd9ee7b3deb",
          "sha256": "c6f0c3d96c90739e336cf17022748fbc72f636681fed9679e1e2bcc39bb10f93",
          "sha1": "71f50ea16a0a77f193cf544350f4927d3e4ebc23",
          "md5": "c63aa28157ccc75dfc4ab8e91bb8c7b6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kanban-0.0.1.21110918-SNAPSHOT.aar",
          "url": "kanban-0.0.1.21110918-20220106.164511-3.aar",
          "size": 44476,
          "sha512": "f46001777ad3339b09df85089fc16406764e576b38c406b4bd535d330ba30858486b27591d5ca17ae4f941ae35e4e7a57fb272ea273264f0137b4cd9ee7b3deb",
          "sha256": "c6f0c3d96c90739e336cf17022748fbc72f636681fed9679e1e2bcc39bb10f93",
          "sha1": "71f50ea16a0a77f193cf544350f4927d3e4ebc23",
          "md5": "c63aa28157ccc75dfc4ab8e91bb8c7b6"
        }
      ]
    }
  ]
}
