{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21091617-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "oil4utiws5cinjlpiox4s76tii"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21091617-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21091617-20210916.090941-1.aar",
          "size": 138260,
          "sha512": "7606f23e8434cae7886d6aac77cb5a99a2b869204d7c307d75c3a9659daed0e055171872c9b43457c51368dc92bff26881e5635f36006a387f5be23dcb3a5f7d",
          "sha256": "d4ad87a4a8528eea772f81c5a8817fb72cdc7c658c6d8f3d1bf39c92d54ace10",
          "sha1": "547e26946c867c78985b2b1b303f7f77d6832591",
          "md5": "c522d0f36e66032cbf0a180aebb5e645"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21091617-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21091617-20210916.090941-1.aar",
          "size": 138260,
          "sha512": "7606f23e8434cae7886d6aac77cb5a99a2b869204d7c307d75c3a9659daed0e055171872c9b43457c51368dc92bff26881e5635f36006a387f5be23dcb3a5f7d",
          "sha256": "d4ad87a4a8528eea772f81c5a8817fb72cdc7c658c6d8f3d1bf39c92d54ace10",
          "sha1": "547e26946c867c78985b2b1b303f7f77d6832591",
          "md5": "c522d0f36e66032cbf0a180aebb5e645"
        }
      ]
    }
  ]
}
