{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.22042501-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "32vphfv3gvbftp6aq3b3xewuzi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.22042501-SNAPSHOT.aar",
          "url": "common-0.0.9.22042501-20220424.161559-1.aar",
          "size": 51156,
          "sha512": "ee68da91d7907dc74ee5db8e2930a5a9d8f8e3aeeb96d2a9c5740ecc161e92dbd98982a655f0eaa2c9c28c140dfde3a8a96e4ce536ad43c7162474b44ad06c8e",
          "sha256": "3184b19733dccc53503ed0122061b06a9d4db76524525e5fedb6704f55c8942f",
          "sha1": "5bf19a1364dfe3ee49870bb242051c36c386ffa0",
          "md5": "210e811a0178e4de938722ecd185729a"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.22042501-SNAPSHOT.aar",
          "url": "common-0.0.9.22042501-20220424.161559-1.aar",
          "size": 51156,
          "sha512": "ee68da91d7907dc74ee5db8e2930a5a9d8f8e3aeeb96d2a9c5740ecc161e92dbd98982a655f0eaa2c9c28c140dfde3a8a96e4ce536ad43c7162474b44ad06c8e",
          "sha256": "3184b19733dccc53503ed0122061b06a9d4db76524525e5fedb6704f55c8942f",
          "sha1": "5bf19a1364dfe3ee49870bb242051c36c386ffa0",
          "md5": "210e811a0178e4de938722ecd185729a"
        }
      ]
    }
  ]
}
