{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.22042500-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nog2msi3gzbpri53jifj4pnj6y"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.22042500-SNAPSHOT.aar",
          "url": "common-0.0.9.22042500-20220424.155700-1.aar",
          "size": 51159,
          "sha512": "47f861075ac7ac1653ffced7127a56d719458b739ef2eacec879ed31e1d69b911ce9340175eb6feab704d9550286b372fc93ba74c9f850bd7a418185ba595b5b",
          "sha256": "807456abb06838b753f35c5c76c23d9dc0cac3450d68cc285e6b8dc92a57b2f7",
          "sha1": "2af49ba2ac38d41b9f6084294e49f176b1fecad0",
          "md5": "58d9b3a0c19024a56dfd5cd2c3d35117"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.22042500-SNAPSHOT.aar",
          "url": "common-0.0.9.22042500-20220424.155700-1.aar",
          "size": 51159,
          "sha512": "47f861075ac7ac1653ffced7127a56d719458b739ef2eacec879ed31e1d69b911ce9340175eb6feab704d9550286b372fc93ba74c9f850bd7a418185ba595b5b",
          "sha256": "807456abb06838b753f35c5c76c23d9dc0cac3450d68cc285e6b8dc92a57b2f7",
          "sha1": "2af49ba2ac38d41b9f6084294e49f176b1fecad0",
          "md5": "58d9b3a0c19024a56dfd5cd2c3d35117"
        }
      ]
    }
  ]
}
