{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zlp6jtw7wreb3hzgrqlr7ixxkq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201025.071108-5.aar",
          "size": 35272,
          "sha512": "c696c0f7d712482f50222b0de7cfb1d2e333ae42aff4a71c86cf74855804fbc11bcc17bb96780f291cce0a20a767affe1e0f3639c4b7e167420011b3ca48c8ad",
          "sha256": "f8b703b49883cb7ed6112b69e9bedf511848f0bf97132e4f06e9a9a1d4a5dbc4",
          "sha1": "1d3dfce830fdb2ea963653ed8ea7f6d9354e4cfc",
          "md5": "cb153ddb9b74ef46af482d7d9f7582a0"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201025.071108-5.aar",
          "size": 35272,
          "sha512": "c696c0f7d712482f50222b0de7cfb1d2e333ae42aff4a71c86cf74855804fbc11bcc17bb96780f291cce0a20a767affe1e0f3639c4b7e167420011b3ca48c8ad",
          "sha256": "f8b703b49883cb7ed6112b69e9bedf511848f0bf97132e4f06e9a9a1d4a5dbc4",
          "sha1": "1d3dfce830fdb2ea963653ed8ea7f6d9354e4cfc",
          "md5": "cb153ddb9b74ef46af482d7d9f7582a0"
        }
      ]
    }
  ]
}
