{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21020604-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "bfwyv4jxfzhk5adgppumfd76xi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020604-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020604-20210205.183139-1.aar",
          "size": 136087,
          "sha512": "b2069b734943a0f4cb887248ec16071eff6a4b85048b2ba1b3fee5c8e80aaadfca6875587449561b5594204c2f241c0455df4ad00bb0835108d252764bfac412",
          "sha256": "9787954859dba42f0d6162268c59ea0da6e72adc6c9842bd1afb2a6c3a96dee8",
          "sha1": "42f6b40b01cd9f777e0a2bbcd0987fc5a3cf8d4c",
          "md5": "4c881d8a5963302c624561abef9bc2f5"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020604-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020604-20210205.183139-1.aar",
          "size": 136087,
          "sha512": "b2069b734943a0f4cb887248ec16071eff6a4b85048b2ba1b3fee5c8e80aaadfca6875587449561b5594204c2f241c0455df4ad00bb0835108d252764bfac412",
          "sha256": "9787954859dba42f0d6162268c59ea0da6e72adc6c9842bd1afb2a6c3a96dee8",
          "sha1": "42f6b40b01cd9f777e0a2bbcd0987fc5a3cf8d4c",
          "md5": "4c881d8a5963302c624561abef9bc2f5"
        }
      ]
    }
  ]
}
