{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "73b5kjcxw5a3pj7ncg7qg5nkbm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201103.153933-3.aar",
          "size": 132737,
          "sha512": "774886e4ba7d1363ca5958714a024066436e9c89efe38a905234798950f0ff6db7466ab4e9c436e27fb97793b9c6d6cef2393172846888d492073b36f3e002fb",
          "sha256": "5516d37770e976f7220fa58adc4d92a7912e65c1add1fbb34a9db09c47cc6519",
          "sha1": "d8cabcfcb1380788cfcd953078fa413ef2b226d5",
          "md5": "7b4041cb5edd5f0bec2332dc1b958248"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201103.153933-3.aar",
          "size": 132737,
          "sha512": "774886e4ba7d1363ca5958714a024066436e9c89efe38a905234798950f0ff6db7466ab4e9c436e27fb97793b9c6d6cef2393172846888d492073b36f3e002fb",
          "sha256": "5516d37770e976f7220fa58adc4d92a7912e65c1add1fbb34a9db09c47cc6519",
          "sha1": "d8cabcfcb1380788cfcd953078fa413ef2b226d5",
          "md5": "7b4041cb5edd5f0bec2332dc1b958248"
        }
      ]
    }
  ]
}
