{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "kanban",
    "version": "0.0.1.21042117-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "eb7vntvlvfbrjghoooqxtsccba"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kanban-0.0.1.21042117-SNAPSHOT.aar",
          "url": "kanban-0.0.1.21042117-20210421.092516-1.aar",
          "size": 46910,
          "sha512": "bf3b57df8a8cbf0f0c21643045926bbc86acca7730b1c8adcd470ad4c0e2bbb1688c8de38d5b78f9507d61765174009d5ca61fdc497584d44c817fffba38ca1b",
          "sha256": "600bcefa7d95abbbd9c1151a0830ef37e661b33b1876d3d9d6c85a5e04a55343",
          "sha1": "ca8d6cc00106523193efe61229bf292b29abe7b4",
          "md5": "7b2a0d215ff650aef5eeda851a31733d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kanban-0.0.1.21042117-SNAPSHOT.aar",
          "url": "kanban-0.0.1.21042117-20210421.092516-1.aar",
          "size": 46910,
          "sha512": "bf3b57df8a8cbf0f0c21643045926bbc86acca7730b1c8adcd470ad4c0e2bbb1688c8de38d5b78f9507d61765174009d5ca61fdc497584d44c817fffba38ca1b",
          "sha256": "600bcefa7d95abbbd9c1151a0830ef37e661b33b1876d3d9d6c85a5e04a55343",
          "sha1": "ca8d6cc00106523193efe61229bf292b29abe7b4",
          "md5": "7b2a0d215ff650aef5eeda851a31733d"
        }
      ]
    }
  ]
}
