{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "dkowsxwwlvahderrvpkkoyrtq4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201021.090437-18.aar",
          "size": 119606,
          "sha512": "3e3cb420be5c23c48aa6202e30235d84fa8cddc3e6d6cf166f6b5b9911afe062ac89f5a11d6c598df6f7ca65fdf9e05cfbdd42b93304fc8cdaee4633b116dd1d",
          "sha256": "d98c146a56d593f92d3fc6f4da4a2f773d519fd62c37192097b822be5ff9df0c",
          "sha1": "640fd3203dced0963dc25d57dbcca3cdab76f48b",
          "md5": "ba8ada7da39ad6b27ac3b25c5e0cc6e6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201021.090437-18.aar",
          "size": 119606,
          "sha512": "3e3cb420be5c23c48aa6202e30235d84fa8cddc3e6d6cf166f6b5b9911afe062ac89f5a11d6c598df6f7ca65fdf9e05cfbdd42b93304fc8cdaee4633b116dd1d",
          "sha256": "d98c146a56d593f92d3fc6f4da4a2f773d519fd62c37192097b822be5ff9df0c",
          "sha1": "640fd3203dced0963dc25d57dbcca3cdab76f48b",
          "md5": "ba8ada7da39ad6b27ac3b25c5e0cc6e6"
        }
      ]
    }
  ]
}
