{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.220050820-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "g5gmlgslprgfrm3ngojfs5ikg4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.220050820-SNAPSHOT.aar",
          "url": "common-0.0.9.220050820-20220508.124939-1.aar",
          "size": 54683,
          "sha512": "dfd1360525ba565b2359cae79035b8ba174a62507e35bf0df5d49e52564bbecb292defce072285df360d3df9663edcc6d7f9546a8b6f4932f4df987486363fa3",
          "sha256": "c7c0bada007e6bba369bc82bf54898efe9768d990d3e60558977cbb30d0be287",
          "sha1": "ee5ab05c03325ebb359a54c74cc133dc177b0765",
          "md5": "39cac49223904e0e07a2ccd0e9dd9ec1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.220050820-SNAPSHOT.aar",
          "url": "common-0.0.9.220050820-20220508.124939-1.aar",
          "size": 54683,
          "sha512": "dfd1360525ba565b2359cae79035b8ba174a62507e35bf0df5d49e52564bbecb292defce072285df360d3df9663edcc6d7f9546a8b6f4932f4df987486363fa3",
          "sha256": "c7c0bada007e6bba369bc82bf54898efe9768d990d3e60558977cbb30d0be287",
          "sha1": "ee5ab05c03325ebb359a54c74cc133dc177b0765",
          "md5": "39cac49223904e0e07a2ccd0e9dd9ec1"
        }
      ]
    }
  ]
}
