{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2302222001-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "oj32cpkkxbej7oo3hjgr22lqri"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222001-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222001-20230222.125617-1.aar",
          "size": 185249,
          "sha512": "67a5da977ea74e1985308bf6b66e2a81c8efc0dc52b748cf833f530d8da27ee02759f8986cb7695b44bd6ffc97e693c0a4861b3b5894413926135eb181f69d51",
          "sha256": "e725fd8914ce7ebac88fd30526e94223585e38ad62b897763f4bd7d9003bcab2",
          "sha1": "547a0422b5d9956271608b1b8e49698891e5f0e8",
          "md5": "fcf4009061e033d7af7c6283a00bd3e0"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222001-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222001-20230222.125617-1.aar",
          "size": 185249,
          "sha512": "67a5da977ea74e1985308bf6b66e2a81c8efc0dc52b748cf833f530d8da27ee02759f8986cb7695b44bd6ffc97e693c0a4861b3b5894413926135eb181f69d51",
          "sha256": "e725fd8914ce7ebac88fd30526e94223585e38ad62b897763f4bd7d9003bcab2",
          "sha1": "547a0422b5d9956271608b1b8e49698891e5f0e8",
          "md5": "fcf4009061e033d7af7c6283a00bd3e0"
        }
      ]
    }
  ]
}
