{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012004-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5bqkpc53nfcejngu474emi3erm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012004-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012004-20210119.184423-1.aar",
          "size": 42106,
          "sha512": "16b9a501053b7d9f6ed343ee73e233f7fe2af6d64e52cec617c23517831a522fd553a19cbb0ad6a73c24d58a8e9b1ef7cac97af70dfc3a7ce25d50417703b907",
          "sha256": "9913c885425a6ef4c5d33de2acc14911898a2503e68d5051a054644ee188ce26",
          "sha1": "23d57851001282f2be29fbd089e7943781dfd133",
          "md5": "d155e14277aca4bee063d64f1d9ace1c"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012004-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012004-20210119.184423-1.aar",
          "size": 42106,
          "sha512": "16b9a501053b7d9f6ed343ee73e233f7fe2af6d64e52cec617c23517831a522fd553a19cbb0ad6a73c24d58a8e9b1ef7cac97af70dfc3a7ce25d50417703b907",
          "sha256": "9913c885425a6ef4c5d33de2acc14911898a2503e68d5051a054644ee188ce26",
          "sha1": "23d57851001282f2be29fbd089e7943781dfd133",
          "md5": "d155e14277aca4bee063d64f1d9ace1c"
        }
      ]
    }
  ]
}
