{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "dprtorqbbvdndefe6hkhtv3nn4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201020.180456-15.aar",
          "size": 121048,
          "sha512": "0fdd10c8f3ad3d03c27a4ecc7ae43f121c253ba58d8f2d3e4f278d4c94bfb8181d1fba57ab3aeb36672cddc8ab54a47d237e7f45aa8389d7caa7e8c04c44ee1e",
          "sha256": "54223345be23af4b1d074d15ce2bbf60c353a5978520de134958604b1085dd8a",
          "sha1": "9d898cbf29c61b64e6646d7877344d05ec0ad328",
          "md5": "258eb659e9a0a2b705e1c0e9f06b3f2f"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201020.180456-15.aar",
          "size": 121048,
          "sha512": "0fdd10c8f3ad3d03c27a4ecc7ae43f121c253ba58d8f2d3e4f278d4c94bfb8181d1fba57ab3aeb36672cddc8ab54a47d237e7f45aa8389d7caa7e8c04c44ee1e",
          "sha256": "54223345be23af4b1d074d15ce2bbf60c353a5978520de134958604b1085dd8a",
          "sha1": "9d898cbf29c61b64e6646d7877344d05ec0ad328",
          "md5": "258eb659e9a0a2b705e1c0e9f06b3f2f"
        }
      ]
    }
  ]
}
