{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ilgd7mrayzbwtkzv2ox4xpogxi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.3.aar",
          "url": "recyclerview-0.9.3.aar",
          "size": 105816,
          "sha512": "f1ef10c26cacd38ecce570207c2197415079abb887aeef10d04087f61e13b34f9bba74eb6e07ca61891fb081bc14b99d8cef7065c85d60534f92743430d1b71d",
          "sha256": "ce86189780566046cb5b371ed4a3764a282a550cfdc3607dd59d84d91e50cc5d",
          "sha1": "73c24bbffc688def0a9c1539754b283162d932c5",
          "md5": "874b530a886529cb3c1317cc1f310013"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.3.aar",
          "url": "recyclerview-0.9.3.aar",
          "size": 105816,
          "sha512": "f1ef10c26cacd38ecce570207c2197415079abb887aeef10d04087f61e13b34f9bba74eb6e07ca61891fb081bc14b99d8cef7065c85d60534f92743430d1b71d",
          "sha256": "ce86189780566046cb5b371ed4a3764a282a550cfdc3607dd59d84d91e50cc5d",
          "sha1": "73c24bbffc688def0a9c1539754b283162d932c5",
          "md5": "874b530a886529cb3c1317cc1f310013"
        }
      ]
    }
  ]
}
