{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012002-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "e5463b3yyjbjphx4voxu6kcqpi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012002-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012002-20210119.183304-1.aar",
          "size": 42170,
          "sha512": "c15b0c6828dc388ffeeff18f303f4d4da510d9921af5936f839069bcf03e7e1b04004ca9684b525a64ad3ba63364b0fe340d6a801860e83582152568f82d40f7",
          "sha256": "cced1120347c3bd2c7e8c55debb7ad5aad9ed5df29eec12451a95e7bb5983311",
          "sha1": "8a638ae6dc198abae3eb5e825683b6d2ba4737dd",
          "md5": "d32d3ca0dd63aea18cf7914bf4b91bf2"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012002-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012002-20210119.183304-1.aar",
          "size": 42170,
          "sha512": "c15b0c6828dc388ffeeff18f303f4d4da510d9921af5936f839069bcf03e7e1b04004ca9684b525a64ad3ba63364b0fe340d6a801860e83582152568f82d40f7",
          "sha256": "cced1120347c3bd2c7e8c55debb7ad5aad9ed5df29eec12451a95e7bb5983311",
          "sha1": "8a638ae6dc198abae3eb5e825683b6d2ba4737dd",
          "md5": "d32d3ca0dd63aea18cf7914bf4b91bf2"
        }
      ]
    }
  ]
}
