{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2207050101-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7rf3tml2j5fkhadqoe7tr4zozi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2207050101-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2207050101-20220704.171924-1.aar",
          "size": 158290,
          "sha512": "b65bf6edec5a3179532d4aee3eabc2cc48d4390c3ecdfa9d4e586f268293f23590f2f4e123983f3afc54cc116310a06a2d9ef471636eaac803e26e192c465072",
          "sha256": "a09a06747d8770f25cef3dd20399778a2d832bcbc0a5fbd3c5a8c6a684ac2158",
          "sha1": "20463d98cbf080c2c83aedd965f092e433c79810",
          "md5": "ad94bb79c1d923b200e48b4faf4277a6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22040815-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2207050101-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2207050101-20220704.171924-1.aar",
          "size": 158290,
          "sha512": "b65bf6edec5a3179532d4aee3eabc2cc48d4390c3ecdfa9d4e586f268293f23590f2f4e123983f3afc54cc116310a06a2d9ef471636eaac803e26e192c465072",
          "sha256": "a09a06747d8770f25cef3dd20399778a2d832bcbc0a5fbd3c5a8c6a684ac2158",
          "sha1": "20463d98cbf080c2c83aedd965f092e433c79810",
          "md5": "ad94bb79c1d923b200e48b4faf4277a6"
        }
      ]
    }
  ]
}
