{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2201252201-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kxsau4ulxjfdbiofnjnlu7nhfm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2201252201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2201252201-20220125.143335-1.aar",
          "size": 123047,
          "sha512": "07f7fab42b142e2d72be636d1aa61086abc60fb187c90e419133cf7838e059bbead699823f27056506d0b4688a0874d7c23939701e6df6b663cc34251e66e501",
          "sha256": "27142088646d4adb88c4078fb540e3f932ca998e7fa64ec1bc3f4304a7119023",
          "sha1": "a04e0f6d9c042007af34ffbc8e01bfe7e16af094",
          "md5": "bd684c1cf8f229223751cc981d5034ac"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2201252201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2201252201-20220125.143335-1.aar",
          "size": 123047,
          "sha512": "07f7fab42b142e2d72be636d1aa61086abc60fb187c90e419133cf7838e059bbead699823f27056506d0b4688a0874d7c23939701e6df6b663cc34251e66e501",
          "sha256": "27142088646d4adb88c4078fb540e3f932ca998e7fa64ec1bc3f4304a7119023",
          "sha1": "a04e0f6d9c042007af34ffbc8e01bfe7e16af094",
          "md5": "bd684c1cf8f229223751cc981d5034ac"
        }
      ]
    }
  ]
}
