{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22030211-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "j4gs3dspgnduhd2agg2o2pcrqy"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22030211-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22030211-20220302.033815-1.aar",
          "size": 123118,
          "sha512": "476b904df6fbabb221178b224a128eac19ef33f751619ac4827675a540ae8c8f17fe6179772ff7e021bf2665441aa85b75a5a99e7f6637582d55c350a8bb48bc",
          "sha256": "a3be757d046e998945cf509731b4d5274d1b0c84c294b7587f18304a5b34923b",
          "sha1": "2afe589c8c6987bf7632408abe0d5dbc7f65ac20",
          "md5": "995eda26dfffbf87a60ceb9856fe29fc"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22030211-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22030211-20220302.033815-1.aar",
          "size": 123118,
          "sha512": "476b904df6fbabb221178b224a128eac19ef33f751619ac4827675a540ae8c8f17fe6179772ff7e021bf2665441aa85b75a5a99e7f6637582d55c350a8bb48bc",
          "sha256": "a3be757d046e998945cf509731b4d5274d1b0c84c294b7587f18304a5b34923b",
          "sha1": "2afe589c8c6987bf7632408abe0d5dbc7f65ac20",
          "md5": "995eda26dfffbf87a60ceb9856fe29fc"
        }
      ]
    }
  ]
}
