{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012104-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kmd4lj35bfeg3ebqc22nsem5ei"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012104-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012104-20210120.184250-1.aar",
          "size": 45469,
          "sha512": "91f8f8ce32248aee63fff278a61744bceae003a274cc986ccf3aced9fdeb0994aa4a94e06ea3954603d0f5da4e75a80acf8a1c017c2d9c859f5bdb44e8ede8ea",
          "sha256": "960bbd5fe26da445a655e15f48341e46012b6f8c80de5a565eff2156365c14fa",
          "sha1": "8576fcd15c67a3bf78c48b47a5a775f3854e3a2a",
          "md5": "ddf0e84864a238d3b8efb67a243fb2c1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012104-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012104-20210120.184250-1.aar",
          "size": 45469,
          "sha512": "91f8f8ce32248aee63fff278a61744bceae003a274cc986ccf3aced9fdeb0994aa4a94e06ea3954603d0f5da4e75a80acf8a1c017c2d9c859f5bdb44e8ede8ea",
          "sha256": "960bbd5fe26da445a655e15f48341e46012b6f8c80de5a565eff2156365c14fa",
          "sha1": "8576fcd15c67a3bf78c48b47a5a775f3854e3a2a",
          "md5": "ddf0e84864a238d3b8efb67a243fb2c1"
        }
      ]
    }
  ]
}
