{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.22122613-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "adwrl5rksjbdjbig253h56kava"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.22122613-SNAPSHOT.aar",
          "url": "common-0.0.9.22122613-20230117.112617-2.aar",
          "size": 55991,
          "sha512": "25b3fae7afc1cea2c7e2aa4ce6b361518825e40f2b960bd88956e670f00cda5be5d90c1c96a8b29aa4b74712cff2df4afb9c66746e039cd26669d570110b55b8",
          "sha256": "78af89868480810dd35f5ef56d7b7a95a12a39ffed6b5e412b6f66ab32181f54",
          "sha1": "8eb77c079a0d96d4111ddcb34f5de4e6157c9bf6",
          "md5": "df4b4a8f01c6730784e23e09b3e25136"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.22122613-SNAPSHOT.aar",
          "url": "common-0.0.9.22122613-20230117.112617-2.aar",
          "size": 55991,
          "sha512": "25b3fae7afc1cea2c7e2aa4ce6b361518825e40f2b960bd88956e670f00cda5be5d90c1c96a8b29aa4b74712cff2df4afb9c66746e039cd26669d570110b55b8",
          "sha256": "78af89868480810dd35f5ef56d7b7a95a12a39ffed6b5e412b6f66ab32181f54",
          "sha1": "8eb77c079a0d96d4111ddcb34f5de4e6157c9bf6",
          "md5": "df4b4a8f01c6730784e23e09b3e25136"
        }
      ]
    }
  ]
}
