{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22102902-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "45i27qxnqzhc7kcr35vehdfvbu"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22102902-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22102902-20221028.181134-1.aar",
          "size": 171764,
          "sha512": "b9bdefd191366184548ae522a0b895019c8863e08d8a8fbd3975e70a1542e18675ed98c5f4d3914105e8263b183b176dd98d154d82c61623cec6ddd496027826",
          "sha256": "0f71b2be905e0774bfc4d74056cb98b663599795232097c659fb6550e99b9f19",
          "sha1": "908a217dd31c936b9f2f07cf5486f0a5201ad239",
          "md5": "9e0ff7403394dd74bf3c3f462644b5bb"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22102902-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22102902-20221028.181134-1.aar",
          "size": 171764,
          "sha512": "b9bdefd191366184548ae522a0b895019c8863e08d8a8fbd3975e70a1542e18675ed98c5f4d3914105e8263b183b176dd98d154d82c61623cec6ddd496027826",
          "sha256": "0f71b2be905e0774bfc4d74056cb98b663599795232097c659fb6550e99b9f19",
          "sha1": "908a217dd31c936b9f2f07cf5486f0a5201ad239",
          "md5": "9e0ff7403394dd74bf3c3f462644b5bb"
        }
      ]
    }
  ]
}
