{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2307182203-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2307182203-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2307182203-SNAPSHOT.aar",
          "size": 187410,
          "sha512": "571e84e5df3ae98e554f63216d3b3b2e96b7f0c6fdb92f67de8b3a7d0210ffb4c671df102e083b6f8ad60383df0e5c52ccf36f491fcfa6522905c6ffca278a93",
          "sha256": "b583ccb1e68bdd31b87c50a4bd7947e2dc57509995337847d67985fcc2c33d83",
          "sha1": "5c459d0d19447c7c367beb0639fcfc81a61467a1",
          "md5": "72593f61fcd83065bd4b573cf416d6df"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2307182203-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2307182203-SNAPSHOT.aar",
          "size": 187410,
          "sha512": "571e84e5df3ae98e554f63216d3b3b2e96b7f0c6fdb92f67de8b3a7d0210ffb4c671df102e083b6f8ad60383df0e5c52ccf36f491fcfa6522905c6ffca278a93",
          "sha256": "b583ccb1e68bdd31b87c50a4bd7947e2dc57509995337847d67985fcc2c33d83",
          "sha1": "5c459d0d19447c7c367beb0639fcfc81a61467a1",
          "md5": "72593f61fcd83065bd4b573cf416d6df"
        }
      ]
    }
  ]
}
