{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2206280201-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2yfvxbbsy5hszfphla3slqcnfy"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2206280201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2206280201-20220627.181907-1.aar",
          "size": 155678,
          "sha512": "5fd0d6362decdee12f22308ede6fa62d71b904eb60e842245c9ac4484000afd45a5e4319c2bd7835ed8efcca6d0e7c2d796684d1756f07eec3289f63c475adb9",
          "sha256": "8486cdfa8eb7321cb94176d77897fce429dc5c5c5dd3c2205058ae70ec2ce8c4",
          "sha1": "f8f7d436436dbfbf01314efac71a56eb1d92d93b",
          "md5": "8955691895ce3a2257292868dd9b1ee8"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22040815-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2206280201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2206280201-20220627.181907-1.aar",
          "size": 155678,
          "sha512": "5fd0d6362decdee12f22308ede6fa62d71b904eb60e842245c9ac4484000afd45a5e4319c2bd7835ed8efcca6d0e7c2d796684d1756f07eec3289f63c475adb9",
          "sha256": "8486cdfa8eb7321cb94176d77897fce429dc5c5c5dd3c2205058ae70ec2ce8c4",
          "sha1": "f8f7d436436dbfbf01314efac71a56eb1d92d93b",
          "md5": "8955691895ce3a2257292868dd9b1ee8"
        }
      ]
    }
  ]
}
