{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.22011018-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jvmnoxe7xzez5e3hqaqzacc5hi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.22011018-SNAPSHOT.aar",
          "url": "common-0.0.9.22011018-20220110.103712-1.aar",
          "size": 48621,
          "sha512": "b76369cee237604e3e955cee3555e24d9e1bdfdfa08da7dea470e321ed7bb61ae3cc4558c20400d3ce34d219daac07e8d3467ec9a0d2b8d8e270a75fbb951a2c",
          "sha256": "4800f6e9a92f19fd5df9b8335d6e92e6ac2b1a489ca2ed51bac3d9d0d18e4c53",
          "sha1": "c6b8d9402f85682cbcea130885b7d07ce38fb201",
          "md5": "3aada5000f6d37290273ca30e69ea04f"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.22011018-SNAPSHOT.aar",
          "url": "common-0.0.9.22011018-20220110.103712-1.aar",
          "size": 48621,
          "sha512": "b76369cee237604e3e955cee3555e24d9e1bdfdfa08da7dea470e321ed7bb61ae3cc4558c20400d3ce34d219daac07e8d3467ec9a0d2b8d8e270a75fbb951a2c",
          "sha256": "4800f6e9a92f19fd5df9b8335d6e92e6ac2b1a489ca2ed51bac3d9d0d18e4c53",
          "sha1": "c6b8d9402f85682cbcea130885b7d07ce38fb201",
          "md5": "3aada5000f6d37290273ca30e69ea04f"
        }
      ]
    }
  ]
}
