{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.211107193-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7ieetsi6oraqtpdlwrbvkx3r5q"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.211107193-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.211107193-20211107.123555-1.aar",
          "size": 123095,
          "sha512": "97cf3ff86cb30fcfc5e7a84a2ee2369582aeb932e7ab04eff0feb49ec80d6bd01834e820d6605f66197015566b15722a90f18676a5bf43f09edb17c2e2eb2896",
          "sha256": "107b7ca1f0cb6f5673ac98ad30e5f129d80dcfe6c99c03e1bb667583e530a287",
          "sha1": "514e87dd1ac900817d3b5488b4247d1acb1c775f",
          "md5": "feeef484bb10da706f0e542e09209cd1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.211107193-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.211107193-20211107.123555-1.aar",
          "size": 123095,
          "sha512": "97cf3ff86cb30fcfc5e7a84a2ee2369582aeb932e7ab04eff0feb49ec80d6bd01834e820d6605f66197015566b15722a90f18676a5bf43f09edb17c2e2eb2896",
          "sha256": "107b7ca1f0cb6f5673ac98ad30e5f129d80dcfe6c99c03e1bb667583e530a287",
          "sha1": "514e87dd1ac900817d3b5488b4247d1acb1c775f",
          "md5": "feeef484bb10da706f0e542e09209cd1"
        }
      ]
    }
  ]
}
