{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.220050719-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vkqz7lh66jah7gbbt44t23tji4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.220050719-SNAPSHOT.aar",
          "url": "common-0.0.9.220050719-20220507.165111-1.aar",
          "size": 52633,
          "sha512": "95775d09db8d9047396eb126f7129b206c68bf34a5afd17befed6dfb733d9b654e3ff728259729db4e2e0543aeef4724f8c21b17b384e1200217028b254d16fb",
          "sha256": "8fa81b32ea92cefeb3fea740862edf28d60b72ee33255c32a41f7cd0fd0b823c",
          "sha1": "dd6aa4703796972a87664c0e7df4a446ba962bfa",
          "md5": "fb8ce283c355868d5f3082a58447edba"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.220050719-SNAPSHOT.aar",
          "url": "common-0.0.9.220050719-20220507.165111-1.aar",
          "size": 52633,
          "sha512": "95775d09db8d9047396eb126f7129b206c68bf34a5afd17befed6dfb733d9b654e3ff728259729db4e2e0543aeef4724f8c21b17b384e1200217028b254d16fb",
          "sha256": "8fa81b32ea92cefeb3fea740862edf28d60b72ee33255c32a41f7cd0fd0b823c",
          "sha1": "dd6aa4703796972a87664c0e7df4a446ba962bfa",
          "md5": "fb8ce283c355868d5f3082a58447edba"
        }
      ]
    }
  ]
}
