{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21082304-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "c7wgezrheba3pk33wl2rs6gdy4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21082304-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21082304-20210822.182628-1.aar",
          "size": 137340,
          "sha512": "a9768388dede4fc2a0b34867d689b9c72e8e49a3e397b4b3af4ce82f15c649678721e15e5655c855529c0c748a52d50d20b8b0fef400ac4fe5f55ba6700db7a4",
          "sha256": "dab2a4c67f9a020b9a762866d9c3ccb392c5aa422e17e9b90197ad2c7d4873a3",
          "sha1": "21389ace81832632e3cd7fc97eba6ebaab76afae",
          "md5": "ceba4392308d659afd1c8f8fc0fff40d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21082304-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21082304-20210822.182628-1.aar",
          "size": 137340,
          "sha512": "a9768388dede4fc2a0b34867d689b9c72e8e49a3e397b4b3af4ce82f15c649678721e15e5655c855529c0c748a52d50d20b8b0fef400ac4fe5f55ba6700db7a4",
          "sha256": "dab2a4c67f9a020b9a762866d9c3ccb392c5aa422e17e9b90197ad2c7d4873a3",
          "sha1": "21389ace81832632e3cd7fc97eba6ebaab76afae",
          "md5": "ceba4392308d659afd1c8f8fc0fff40d"
        }
      ]
    }
  ]
}
