{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ilau5gh2rffhjihyrfxdlaoqla"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201018.114600-1.aar",
          "size": 106889,
          "sha512": "a9ea1f769fb475f7c6a358663740544d3f6e92d1e7b034ecbe5ce313ba27d97c23d32d8b2923946128379ab934f014a735981578241513089c011995260cc34f",
          "sha256": "57029cd23bcd94be585dba070c840fbee303198be3936ce54f3773e24cfc0042",
          "sha1": "c9030b9821771b1d86f5f76d3fd821804e84fdfe",
          "md5": "e08dffce9ce79b8e3bfcc33cf4dada2a"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201018.114600-1.aar",
          "size": 106889,
          "sha512": "a9ea1f769fb475f7c6a358663740544d3f6e92d1e7b034ecbe5ce313ba27d97c23d32d8b2923946128379ab934f014a735981578241513089c011995260cc34f",
          "sha256": "57029cd23bcd94be585dba070c840fbee303198be3936ce54f3773e24cfc0042",
          "sha1": "c9030b9821771b1d86f5f76d3fd821804e84fdfe",
          "md5": "e08dffce9ce79b8e3bfcc33cf4dada2a"
        }
      ]
    }
  ]
}
