{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.21110821-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "d6rjwnsg4zccdprzymbswavska"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110821-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110821-20211108.132407-1.aar",
          "size": 127465,
          "sha512": "9dfdc691a2bf0c1846047b582deded722145e4d587c97631aa77542656f24ed1027ad936813b256a42e256c968b70aff8a07ce63a3b856b8aac05ce1b60a1988",
          "sha256": "b90924dc6c5c8bcf8cb22d14cc50dfe603d2c357a9a31104b5c5f156a680692d",
          "sha1": "b2283f347574edb3f62e4a1583683f8b9524a497",
          "md5": "edd69887dfdd888ec25b01448eb037ea"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110821-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110821-20211108.132407-1.aar",
          "size": 127465,
          "sha512": "9dfdc691a2bf0c1846047b582deded722145e4d587c97631aa77542656f24ed1027ad936813b256a42e256c968b70aff8a07ce63a3b856b8aac05ce1b60a1988",
          "sha256": "b90924dc6c5c8bcf8cb22d14cc50dfe603d2c357a9a31104b5c5f156a680692d",
          "sha1": "b2283f347574edb3f62e4a1583683f8b9524a497",
          "md5": "edd69887dfdd888ec25b01448eb037ea"
        }
      ]
    }
  ]
}
