{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mic2zajodjdn5oo3wocmk5d4ye"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201018.130559-2.aar",
          "size": 106969,
          "sha512": "d96fe925bede0e00d4d46733a906ab2e7351a5d8ce955a27e194bc8bf06705aa838e32719673ce55e90daf13afc2ccfe4be9af8071a9986e58cb0256cbe30b91",
          "sha256": "781baec28b85a13ca17980e52beaa763cad72dab0a7a595a427db3b458a93514",
          "sha1": "2201240f7caefbfbd615eb93c42529064865ff87",
          "md5": "58e5069f29e277ddec046b3f371d6f4d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.5-SNAPSHOT.aar",
          "url": "recyclerview-0.9.5-20201018.130559-2.aar",
          "size": 106969,
          "sha512": "d96fe925bede0e00d4d46733a906ab2e7351a5d8ce955a27e194bc8bf06705aa838e32719673ce55e90daf13afc2ccfe4be9af8071a9986e58cb0256cbe30b91",
          "sha256": "781baec28b85a13ca17980e52beaa763cad72dab0a7a595a427db3b458a93514",
          "sha1": "2201240f7caefbfbd615eb93c42529064865ff87",
          "md5": "58e5069f29e277ddec046b3f371d6f4d"
        }
      ]
    }
  ]
}
