{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "uhmycf44jfayzaqzqeqnbzi3zy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.6.aar",
          "url": "common-0.0.6.aar",
          "size": 48245,
          "sha512": "daa0a86bc73c1e1b295ca28a592ca2283341368fda00ec3323587a3739ada7dd018ba894bae31863364d2c476059851a1304fa2f2502c3046ad075f6536cbcef",
          "sha256": "fbdad38ac9edc0360e52c79a36b87af9dbef9d20e28c60bfa4508d0da08ef25f",
          "sha1": "bc96e8d2df31f4d93c1661f9fd8c80229578b14e",
          "md5": "2936a5846dfec77975823a92eca9117a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.6.aar",
          "url": "common-0.0.6.aar",
          "size": 48245,
          "sha512": "daa0a86bc73c1e1b295ca28a592ca2283341368fda00ec3323587a3739ada7dd018ba894bae31863364d2c476059851a1304fa2f2502c3046ad075f6536cbcef",
          "sha256": "fbdad38ac9edc0360e52c79a36b87af9dbef9d20e28c60bfa4508d0da08ef25f",
          "sha1": "bc96e8d2df31f4d93c1661f9fd8c80229578b14e",
          "md5": "2936a5846dfec77975823a92eca9117a"
        }
      ]
    }
  ]
}
