{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22031423-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "avb5zqroxrhshi7lay3mmvuc5q"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22031423-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22031423-20220314.153645-1.aar",
          "size": 123124,
          "sha512": "cee26adad361345415c67a574ab7fe42036227ad153a83a248d908a898226a0f976132151aa46765cc7792800ef6498cb9b9a14d3f707cd000b8fc6c50c65938",
          "sha256": "f3dca338824be023ab7c0c8fe0e8c80b88069953efb476468c65d5d8ebbc76a0",
          "sha1": "5db65a6fbe15188b04363ff58c53fe8594d8780c",
          "md5": "5ab55bce8485e00b3d57d88e7510bd05"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22031423-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22031423-20220314.153645-1.aar",
          "size": 123124,
          "sha512": "cee26adad361345415c67a574ab7fe42036227ad153a83a248d908a898226a0f976132151aa46765cc7792800ef6498cb9b9a14d3f707cd000b8fc6c50c65938",
          "sha256": "f3dca338824be023ab7c0c8fe0e8c80b88069953efb476468c65d5d8ebbc76a0",
          "sha1": "5db65a6fbe15188b04363ff58c53fe8594d8780c",
          "md5": "5ab55bce8485e00b3d57d88e7510bd05"
        }
      ]
    }
  ]
}
