{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "fn6qz4urvnaohpp7ays7ntdtfi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201103.170412-4.aar",
          "size": 134341,
          "sha512": "ca1bbb7735278f95a0a26771a0bd106748d7a0512390279b5822503be9e7753c804f124ff7bbd598f8d70c951d78e671be656e9e1e02b62c63e042fa70ba2caa",
          "sha256": "3201ae0314737b33b6aaa7835d8044a8d2a31bd9f934cbb0457a8cacea5b44e1",
          "sha1": "321ba1b3e38c65e5cc4da253ed84991832216b9e",
          "md5": "568edc9d985231acc4ce3e51ebe06d52"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201103.170412-4.aar",
          "size": 134341,
          "sha512": "ca1bbb7735278f95a0a26771a0bd106748d7a0512390279b5822503be9e7753c804f124ff7bbd598f8d70c951d78e671be656e9e1e02b62c63e042fa70ba2caa",
          "sha256": "3201ae0314737b33b6aaa7835d8044a8d2a31bd9f934cbb0457a8cacea5b44e1",
          "sha1": "321ba1b3e38c65e5cc4da253ed84991832216b9e",
          "md5": "568edc9d985231acc4ce3e51ebe06d52"
        }
      ]
    }
  ]
}
