{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "gthicxsp3bcxdi72q5fsyy6u6i"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201019.150442-3.aar",
          "size": 31481,
          "sha512": "47a5cec4c41299648d511aecf91ae976385b3c767cc17ec85f2a7ede3074b647739006cc00b35277cc17c9b1bc87d74986401fa044098695ef23b650ea4bee55",
          "sha256": "9f6f6f786411017ee04094700231f4be09a3db4728c0353e63736b1e855272b1",
          "sha1": "3c1dbfe4c61cbbe08c4241f3ec93593fd09de042",
          "md5": "e332c54acb27057a98d53b1bfad1113b"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201019.150442-3.aar",
          "size": 31481,
          "sha512": "47a5cec4c41299648d511aecf91ae976385b3c767cc17ec85f2a7ede3074b647739006cc00b35277cc17c9b1bc87d74986401fa044098695ef23b650ea4bee55",
          "sha256": "9f6f6f786411017ee04094700231f4be09a3db4728c0353e63736b1e855272b1",
          "sha1": "3c1dbfe4c61cbbe08c4241f3ec93593fd09de042",
          "md5": "e332c54acb27057a98d53b1bfad1113b"
        }
      ]
    }
  ]
}
