{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.22031623-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "klp3mvykmbc7daqqq2qtoiopey"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.22031623-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.22031623-20220616.150856-1.aar",
          "size": 51008,
          "sha512": "3f2fccc13f4b764c4c61c2798b611c78fcf1316687eb3b35e8c2c129606a7d1fb93e1479a420eecc934af7e2e4c8d13c7570d689f932c07761c7068419c8a04e",
          "sha256": "a32207707c3c60659a1b4b1f55e4b816a3202a4959daa7113951a7f97fdcbddf",
          "sha1": "0f86a6d1079630f5a60721d17b7caccc4c79d048",
          "md5": "3d8604b02113237a9183f19a5fb56e65"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.22031623-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.22031623-20220616.150856-1.aar",
          "size": 51008,
          "sha512": "3f2fccc13f4b764c4c61c2798b611c78fcf1316687eb3b35e8c2c129606a7d1fb93e1479a420eecc934af7e2e4c8d13c7570d689f932c07761c7068419c8a04e",
          "sha256": "a32207707c3c60659a1b4b1f55e4b816a3202a4959daa7113951a7f97fdcbddf",
          "sha1": "0f86a6d1079630f5a60721d17b7caccc4c79d048",
          "md5": "3d8604b02113237a9183f19a5fb56e65"
        }
      ]
    }
  ]
}
