{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vlkifnrm45cmzc767qmhdu6nya"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201019.120708-1.aar",
          "size": 27096,
          "sha512": "e1e3d5782ba4b90cb7d972e0ff518f7c9e7f5edb11b47b9bfe173bcb6fa50ce58872a3473d5416eb1d89f4909db10b73459f181e81e9aa2dc8bd34b85d2abae9",
          "sha256": "1629da7156c80a9da6edd1a3134ea5e1159a6274fe4ae9b745a52e273a59b5f3",
          "sha1": "85f7153005d6d89c7a46be945a0ba9558e072098",
          "md5": "68b5ffc38a22ba5f57026a77e9119df3"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201019.120708-1.aar",
          "size": 27096,
          "sha512": "e1e3d5782ba4b90cb7d972e0ff518f7c9e7f5edb11b47b9bfe173bcb6fa50ce58872a3473d5416eb1d89f4909db10b73459f181e81e9aa2dc8bd34b85d2abae9",
          "sha256": "1629da7156c80a9da6edd1a3134ea5e1159a6274fe4ae9b745a52e273a59b5f3",
          "sha1": "85f7153005d6d89c7a46be945a0ba9558e072098",
          "md5": "68b5ffc38a22ba5f57026a77e9119df3"
        }
      ]
    }
  ]
}
