{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22122320-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "r7jmtsgx3jfxtbbj3xxd264ime"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22122320-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22122320-20221223.122846-1.aar",
          "size": 176020,
          "sha512": "a0b7f19479b5573b08140ad3aded0a1906230516f407a2cd538d780b0349bf029cf0634720510eddbdce4bd6e84937e24531b48ed0bae73288c49ffa0ff5aba3",
          "sha256": "9c81c2520cae1edfb8d48d7ab0ec36710f5cddeb7a25ee37414f8eb48d800653",
          "sha1": "2a6b5640acadae0f4a555e7f753319d4316bb71e",
          "md5": "fc4b83ffc2800a507947bb6dca3b166f"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22122320-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22122320-20221223.122846-1.aar",
          "size": 176020,
          "sha512": "a0b7f19479b5573b08140ad3aded0a1906230516f407a2cd538d780b0349bf029cf0634720510eddbdce4bd6e84937e24531b48ed0bae73288c49ffa0ff5aba3",
          "sha256": "9c81c2520cae1edfb8d48d7ab0ec36710f5cddeb7a25ee37414f8eb48d800653",
          "sha1": "2a6b5640acadae0f4a555e7f753319d4316bb71e",
          "md5": "fc4b83ffc2800a507947bb6dca3b166f"
        }
      ]
    }
  ]
}
