{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.flutter",
    "module": "nestedflutterview",
    "version": "1.0.0.23011617-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nestedflutterview-1.0.0.23011617-SNAPSHOT.aar",
          "url": "nestedflutterview-1.0.0.23011617-SNAPSHOT.aar",
          "size": 11115,
          "sha512": "ac3257d2228c9b36305a4d075d3bee7536b78a84dd9d9b2c37681a932da279f70809e775d0dc2110b6088995888e50f7dbe96a5306d3b7e46048a07d8400c542",
          "sha256": "b7145912f8473c19c5b91580c780ab2f0ca4741b6f2143c0d4b353b376046804",
          "sha1": "9d1a70937496a8a94cfaa639346cc73252e3a670",
          "md5": "eee9fb8ccca9ac817b902b016375b154"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nestedflutterview-1.0.0.23011617-SNAPSHOT.aar",
          "url": "nestedflutterview-1.0.0.23011617-SNAPSHOT.aar",
          "size": 11115,
          "sha512": "ac3257d2228c9b36305a4d075d3bee7536b78a84dd9d9b2c37681a932da279f70809e775d0dc2110b6088995888e50f7dbe96a5306d3b7e46048a07d8400c542",
          "sha256": "b7145912f8473c19c5b91580c780ab2f0ca4741b6f2143c0d4b353b376046804",
          "sha1": "9d1a70937496a8a94cfaa639346cc73252e3a670",
          "md5": "eee9fb8ccca9ac817b902b016375b154"
        }
      ]
    }
  ]
}
