{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.23102402-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23102402-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23102402-SNAPSHOT.aar",
          "size": 187715,
          "sha512": "c865a7972416116b31cb8d7d13e5fdd632b6edce168ac415baf0df5c907900b67628d776e4f4fe53386b6db79bfa1c5ca025ad3a31ba98a7752646ce1521a2ca",
          "sha256": "f86f91701ea3b9d590c154b1c0063c3f2b8a707b40c2ca6fb06af57ff505ddce",
          "sha1": "9b365f149a11ac5d15884aab6f071d7c10d65849",
          "md5": "02c63750c18ec56047d9800f85cef4f6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23102402-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23102402-SNAPSHOT.aar",
          "size": 187715,
          "sha512": "c865a7972416116b31cb8d7d13e5fdd632b6edce168ac415baf0df5c907900b67628d776e4f4fe53386b6db79bfa1c5ca025ad3a31ba98a7752646ce1521a2ca",
          "sha256": "f86f91701ea3b9d590c154b1c0063c3f2b8a707b40c2ca6fb06af57ff505ddce",
          "sha1": "9b365f149a11ac5d15884aab6f071d7c10d65849",
          "md5": "02c63750c18ec56047d9800f85cef4f6"
        }
      ]
    }
  ]
}
