{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2307182205-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2307182205-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2307182205-SNAPSHOT.aar",
          "size": 187925,
          "sha512": "36bd750db507d3eead3feacb2564edf67d3a96c464015685db08894b138fbd4f15caeaa6b21309f2b25ca64af26dec68176c82b00a6053d937c0e43139007719",
          "sha256": "29458d3942d2565f671aa95aa2d80df70a1a964889418f25ecdf5c31e043d3d8",
          "sha1": "ff52d89ff427bd20c86cbc20bd88bf5a2bd4f45b",
          "md5": "19edd42c6bbbc86d27c7d19344ad9d2c"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2307182205-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2307182205-SNAPSHOT.aar",
          "size": 187925,
          "sha512": "36bd750db507d3eead3feacb2564edf67d3a96c464015685db08894b138fbd4f15caeaa6b21309f2b25ca64af26dec68176c82b00a6053d937c0e43139007719",
          "sha256": "29458d3942d2565f671aa95aa2d80df70a1a964889418f25ecdf5c31e043d3d8",
          "sha1": "ff52d89ff427bd20c86cbc20bd88bf5a2bd4f45b",
          "md5": "19edd42c6bbbc86d27c7d19344ad9d2c"
        }
      ]
    }
  ]
}
