{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2302222301-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7zotslwbd5d2hebetzlinb635q"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222301-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222301-20230222.155258-1.aar",
          "size": 186691,
          "sha512": "87f331ed61fc8c277f512e557e86382a76c1a09932c7e074c9dade5c69c0294f60a85fb0873014c597d1236b2bc3a4159fe19650cfe7b935e56a5fd85cffdc21",
          "sha256": "aae13223c613cbbc1e2226f50e6a94cac1ac9b7509016a628ebf3181bb3a6a25",
          "sha1": "837fdd9703bad420f63557101f1f411ff63751aa",
          "md5": "bf416f47b460df91c17bd273a25948f7"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222301-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222301-20230222.155258-1.aar",
          "size": 186691,
          "sha512": "87f331ed61fc8c277f512e557e86382a76c1a09932c7e074c9dade5c69c0294f60a85fb0873014c597d1236b2bc3a4159fe19650cfe7b935e56a5fd85cffdc21",
          "sha256": "aae13223c613cbbc1e2226f50e6a94cac1ac9b7509016a628ebf3181bb3a6a25",
          "sha1": "837fdd9703bad420f63557101f1f411ff63751aa",
          "md5": "bf416f47b460df91c17bd273a25948f7"
        }
      ]
    }
  ]
}
