{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "widgets",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "txzd42tjfnfytabidvxajam5my"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.aar",
          "url": "widgets-0.0.1.aar",
          "size": 20053,
          "sha512": "8d5c1705857705951d285393bff273308250e1c09fc6737cf664055655573ebedb4fbc8f745723f90e09d523af7e5fe188828b784d6b85d6eaf94d296ba078b8",
          "sha256": "cafa4e7714604a1b6ebc747314e1966284191e9fe0b01ae71e7cf6373ff046cf",
          "sha1": "47145c73641f502ada2b4375352b2d06e1254c46",
          "md5": "fac10bd2036499b6cd646e70dac96db0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.aar",
          "url": "widgets-0.0.1.aar",
          "size": 20053,
          "sha512": "8d5c1705857705951d285393bff273308250e1c09fc6737cf664055655573ebedb4fbc8f745723f90e09d523af7e5fe188828b784d6b85d6eaf94d296ba078b8",
          "sha256": "cafa4e7714604a1b6ebc747314e1966284191e9fe0b01ae71e7cf6373ff046cf",
          "sha1": "47145c73641f502ada2b4375352b2d06e1254c46",
          "md5": "fac10bd2036499b6cd646e70dac96db0"
        }
      ]
    }
  ]
}
