{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012013-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "aq2vi5vbbbbgpfvpvmpkg3nzi4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012013-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012013-20210120.054453-1.aar",
          "size": 42488,
          "sha512": "6d4e0afedbf8eed9375158d701a4c15b21585f280f9e61c84ebb984555879b7adcdf0b0b56168a2b299d820954463936fc9ef235400876e9228817dc519e0460",
          "sha256": "207417abeca5b07ba0b286c42a31333deedc17416dc75e8a8eec07599e11c17f",
          "sha1": "9b881c94ea036c18b5d370abb693d62b43a44455",
          "md5": "06cdad8c904a5ae18218b7a9668f45dd"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012013-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012013-20210120.054453-1.aar",
          "size": 42488,
          "sha512": "6d4e0afedbf8eed9375158d701a4c15b21585f280f9e61c84ebb984555879b7adcdf0b0b56168a2b299d820954463936fc9ef235400876e9228817dc519e0460",
          "sha256": "207417abeca5b07ba0b286c42a31333deedc17416dc75e8a8eec07599e11c17f",
          "sha1": "9b881c94ea036c18b5d370abb693d62b43a44455",
          "md5": "06cdad8c904a5ae18218b7a9668f45dd"
        }
      ]
    }
  ]
}
