{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21021517-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2aqi3z6mxbezfjgeavlb55qiea"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21021517-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21021517-20210215.084849-2.aar",
          "size": 136343,
          "sha512": "b1b162e58befb6f5fb37d50e3a1136838b0693ffabd06a475597602490bbbd543320f10546557f04bf232faaa49f40737176003f70b25061f31edd000e8c417c",
          "sha256": "3129f217cdff5336d0fe892b3907343f2857db2b61e74790d7044be36a9a8eb0",
          "sha1": "e3ee1589165f34b113c738262fa48c0d68982f40",
          "md5": "92fe337b3aae8748e39bb50b379e8f28"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21021517-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21021517-20210215.084849-2.aar",
          "size": 136343,
          "sha512": "b1b162e58befb6f5fb37d50e3a1136838b0693ffabd06a475597602490bbbd543320f10546557f04bf232faaa49f40737176003f70b25061f31edd000e8c417c",
          "sha256": "3129f217cdff5336d0fe892b3907343f2857db2b61e74790d7044be36a9a8eb0",
          "sha1": "e3ee1589165f34b113c738262fa48c0d68982f40",
          "md5": "92fe337b3aae8748e39bb50b379e8f28"
        }
      ]
    }
  ]
}
