{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.220050821-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "i34iru6b4rcl3gqsyn5xzx7q7a"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.220050821-SNAPSHOT.aar",
          "url": "common-0.0.9.220050821-20220508.125606-1.aar",
          "size": 54751,
          "sha512": "0d16b538a26450be4926be6f2f1c1aa994671840e9651a11cc5b518bcfa8235434643ce72fc88c86c849314cb6303f04c9ebcfa8c71700cc39b8ab4ab46b5926",
          "sha256": "ba5e0bebb142162d002f34b3dec51405970b88ec5dda21fd64951cefa3a0a939",
          "sha1": "a47fc092858ce260f5c1ebb11fc73a784ceab595",
          "md5": "4ae74e8513781ba914d65a290bb3b55b"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.220050821-SNAPSHOT.aar",
          "url": "common-0.0.9.220050821-20220508.125606-1.aar",
          "size": 54751,
          "sha512": "0d16b538a26450be4926be6f2f1c1aa994671840e9651a11cc5b518bcfa8235434643ce72fc88c86c849314cb6303f04c9ebcfa8c71700cc39b8ab4ab46b5926",
          "sha256": "ba5e0bebb142162d002f34b3dec51405970b88ec5dda21fd64951cefa3a0a939",
          "sha1": "a47fc092858ce260f5c1ebb11fc73a784ceab595",
          "md5": "4ae74e8513781ba914d65a290bb3b55b"
        }
      ]
    }
  ]
}
