{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22111103-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "52cy5tjv6fawnfwvvrt72bzgha"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22111103-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22111103-20221110.191948-1.aar",
          "size": 173335,
          "sha512": "6eab4dbd8c8f61a0b9c88e5e985018eede9aad693c7cd1edf5564d63fab75e01692888b61e4c5635a791e827435eedeb5e01c70e6671376cae6b87f869cab1bd",
          "sha256": "723a2b38b95d699ab1daf8e4517e9b459435047114e69c5783b06389fa8e4b5c",
          "sha1": "3e8402319b0febc074c89398d0c33f497d4a2b6f",
          "md5": "d5c977baff6ff31dc71dfb9a4c1a8dc5"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22111103-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22111103-20221110.191948-1.aar",
          "size": 173335,
          "sha512": "6eab4dbd8c8f61a0b9c88e5e985018eede9aad693c7cd1edf5564d63fab75e01692888b61e4c5635a791e827435eedeb5e01c70e6671376cae6b87f869cab1bd",
          "sha256": "723a2b38b95d699ab1daf8e4517e9b459435047114e69c5783b06389fa8e4b5c",
          "sha1": "3e8402319b0febc074c89398d0c33f497d4a2b6f",
          "md5": "d5c977baff6ff31dc71dfb9a4c1a8dc5"
        }
      ]
    }
  ]
}
