{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22092821-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "d4giwrqzx5a73jkg5svsk4owwe"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22092821-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22092821-20220928.131909-1.aar",
          "size": 164187,
          "sha512": "65226a7102c07f66d196837e251ba5080e2beeced198acf5d024ae8ad10db39e157c8777fd20d092cf8673eb70c4d97bbdf494470c9f5aeeb5f44a9965734562",
          "sha256": "b566e9e9f665472ca850fd7de58284f0fd3cc6e96384ef2dbf82f4cae704f320",
          "sha1": "06ca956172abb68e1ce331790d84911a9ad04ccc",
          "md5": "43f4484dddf4d62b82fbecf7ee64e7bf"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22071000-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22092821-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22092821-20220928.131909-1.aar",
          "size": 164187,
          "sha512": "65226a7102c07f66d196837e251ba5080e2beeced198acf5d024ae8ad10db39e157c8777fd20d092cf8673eb70c4d97bbdf494470c9f5aeeb5f44a9965734562",
          "sha256": "b566e9e9f665472ca850fd7de58284f0fd3cc6e96384ef2dbf82f4cae704f320",
          "sha1": "06ca956172abb68e1ce331790d84911a9ad04ccc",
          "md5": "43f4484dddf4d62b82fbecf7ee64e7bf"
        }
      ]
    }
  ]
}
