{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22102915-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kldwx43qqjac3fsttxgahwnjau"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22102915-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22102915-20221029.072724-1.aar",
          "size": 171713,
          "sha512": "bf583b431c534c8af586947ecfaecf688d137ada58379abf2a0ec455370c9ffcb4c57325d12628a4d6c5618d736474f5f4ab84c38cb1ffef508bdcc244fb2802",
          "sha256": "6c289c7187359e6ae5e1b703b8ed46789bb5a992d408249f09b4c1b358d17843",
          "sha1": "bff8568cd1ec9ffa3875118622e6e6bb34de2dcd",
          "md5": "f9d609a6f7ded735fef04b36a8539b9c"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22102915-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22102915-20221029.072724-1.aar",
          "size": 171713,
          "sha512": "bf583b431c534c8af586947ecfaecf688d137ada58379abf2a0ec455370c9ffcb4c57325d12628a4d6c5618d736474f5f4ab84c38cb1ffef508bdcc244fb2802",
          "sha256": "6c289c7187359e6ae5e1b703b8ed46789bb5a992d408249f09b4c1b358d17843",
          "sha1": "bff8568cd1ec9ffa3875118622e6e6bb34de2dcd",
          "md5": "f9d609a6f7ded735fef04b36a8539b9c"
        }
      ]
    }
  ]
}
