{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21012116-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "lv3ftilssrbtzoc2h2lscbzdy4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21012116-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21012116-20210121.090122-1.aar",
          "size": 134589,
          "sha512": "b0b5384a4c8667a729887665d35e02aca6a964d7109f2d55dfd635efdc2d235f8582a947e6ffb35d4ae643696c77af268fca10d4b7ea3ea74bd6cf440cd9228b",
          "sha256": "829a480b5e6b7624af926da8c9dc0443ee7512442ab9d7351f0cf6824b218050",
          "sha1": "15122038f50a0f722f84067fff0fe33d2bdde638",
          "md5": "e183c0af7aa76ebdde0f8a1bc6f3b955"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21012116-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21012116-20210121.090122-1.aar",
          "size": 134589,
          "sha512": "b0b5384a4c8667a729887665d35e02aca6a964d7109f2d55dfd635efdc2d235f8582a947e6ffb35d4ae643696c77af268fca10d4b7ea3ea74bd6cf440cd9228b",
          "sha256": "829a480b5e6b7624af926da8c9dc0443ee7512442ab9d7351f0cf6824b218050",
          "sha1": "15122038f50a0f722f84067fff0fe33d2bdde638",
          "md5": "e183c0af7aa76ebdde0f8a1bc6f3b955"
        }
      ]
    }
  ]
}
