{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2302222202-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cbsmwhmrpfeytfcae5ushr6pxu"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222202-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222202-20230222.144401-1.aar",
          "size": 185671,
          "sha512": "8cbfe1b72b51d89ca7ea989ff9991229a99c0c30c79ea4a79db925187adb2fd4fd2dfc5a8ceb1e55e2b573f97cca201b2a1917244e43633233677942dfd5e1f7",
          "sha256": "71c478658ae5cd56c0136638e724ef52c33054301fa741cdee493e32045d7400",
          "sha1": "39649a45533a3d5ec3a8bca3319c75b69356a31a",
          "md5": "9a5603f8d3ee846fd5efdf27a419654f"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222202-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222202-20230222.144401-1.aar",
          "size": 185671,
          "sha512": "8cbfe1b72b51d89ca7ea989ff9991229a99c0c30c79ea4a79db925187adb2fd4fd2dfc5a8ceb1e55e2b573f97cca201b2a1917244e43633233677942dfd5e1f7",
          "sha256": "71c478658ae5cd56c0136638e724ef52c33054301fa741cdee493e32045d7400",
          "sha1": "39649a45533a3d5ec3a8bca3319c75b69356a31a",
          "md5": "9a5603f8d3ee846fd5efdf27a419654f"
        }
      ]
    }
  ]
}
