{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21033114-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "wj6hh5vyhvez7jb5ysz2l4poiq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21033114-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21033114-20210331.060019-1.aar",
          "size": 48046,
          "sha512": "a55c409a1011602aee9c3ec0411beeca1b8fcf45d2a1f68e2b5cd0d4888dc1786e20e57870472fe792c4f9d37875582df1e257378c61aade10eef919d91732f8",
          "sha256": "bf38e3cad6fc0508aab03f7161e4a6c0ad0403070ce1fd13d4b5f66be0972b07",
          "sha1": "8ca7eccde5da296db9dedb58640deb497d5dec8c",
          "md5": "24a5f759625c326d999dd69690b7b4e6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21033114-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21033114-20210331.060019-1.aar",
          "size": 48046,
          "sha512": "a55c409a1011602aee9c3ec0411beeca1b8fcf45d2a1f68e2b5cd0d4888dc1786e20e57870472fe792c4f9d37875582df1e257378c61aade10eef919d91732f8",
          "sha256": "bf38e3cad6fc0508aab03f7161e4a6c0ad0403070ce1fd13d4b5f66be0972b07",
          "sha1": "8ca7eccde5da296db9dedb58640deb497d5dec8c",
          "md5": "24a5f759625c326d999dd69690b7b4e6"
        }
      ]
    }
  ]
}
