{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2302222201-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7hfoiv3uwnbc5elfwyklvduw5q"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222201-20230222.142013-1.aar",
          "size": 185590,
          "sha512": "a39e087b737652b6964669d1e6da631b364c1d7f6f7beb53c225f1a9cc494098d6a3aaa5b57aa730d4f7b872b91b708f64339ad7d40b2079f9d9df47c4c17172",
          "sha256": "85b50b901d4575c941fb22b2090d5a48f0c6a24e97657a14819541a1218870df",
          "sha1": "b6c70a835e2a1dbb24a01a2e30f89718b32b2951",
          "md5": "11b0e14bc09cf44fc33873f1d78da573"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2302222201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2302222201-20230222.142013-1.aar",
          "size": 185590,
          "sha512": "a39e087b737652b6964669d1e6da631b364c1d7f6f7beb53c225f1a9cc494098d6a3aaa5b57aa730d4f7b872b91b708f64339ad7d40b2079f9d9df47c4c17172",
          "sha256": "85b50b901d4575c941fb22b2090d5a48f0c6a24e97657a14819541a1218870df",
          "sha1": "b6c70a835e2a1dbb24a01a2e30f89718b32b2951",
          "md5": "11b0e14bc09cf44fc33873f1d78da573"
        }
      ]
    }
  ]
}
