{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012118-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vozwnyz33nh3dfynulrxvxwsae"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012118-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012118-20210121.104348-1.aar",
          "size": 47373,
          "sha512": "79281eaaeffa1dbcdd72ca9dd9f7445e00278dc3ebd7bc366950ad0a661039ad70769f5ca2da36ca80333afd42a0acbe767007f89cabaeea48839651cf545c82",
          "sha256": "715ad0f9d5161d5481bd52644d2bed6e461a905109847e09bf33d940565b4660",
          "sha1": "1e9d7b8cad3e3bcee54ae1e0932b852610751e9f",
          "md5": "6f6ee41c8972734f3cba49459f5e56fa"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012118-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012118-20210121.104348-1.aar",
          "size": 47373,
          "sha512": "79281eaaeffa1dbcdd72ca9dd9f7445e00278dc3ebd7bc366950ad0a661039ad70769f5ca2da36ca80333afd42a0acbe767007f89cabaeea48839651cf545c82",
          "sha256": "715ad0f9d5161d5481bd52644d2bed6e461a905109847e09bf33d940565b4660",
          "sha1": "1e9d7b8cad3e3bcee54ae1e0932b852610751e9f",
          "md5": "6f6ee41c8972734f3cba49459f5e56fa"
        }
      ]
    }
  ]
}
