{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21101402-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vqid6xwvirefpaptptreks5pmy"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21101402-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21101402-20211013.183745-1.aar",
          "size": 139537,
          "sha512": "fc4286ed9d6b9620810ab5b18aaf1642cbbc79e5164c6b94fe5b216d955daee15246288b71fbe9136fc98e766308602dc96832e9498c1ebbfcdceba0203cfdd9",
          "sha256": "d53133b5ea3055536e660af4b37c8182b3ef3f5f3dc5943495420307250cee6b",
          "sha1": "aabd37176198b4e18059c04d1654a1cbc85b546f",
          "md5": "96126c963cd01b4472f665b82a3117bb"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21101402-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21101402-20211013.183745-1.aar",
          "size": 139537,
          "sha512": "fc4286ed9d6b9620810ab5b18aaf1642cbbc79e5164c6b94fe5b216d955daee15246288b71fbe9136fc98e766308602dc96832e9498c1ebbfcdceba0203cfdd9",
          "sha256": "d53133b5ea3055536e660af4b37c8182b3ef3f5f3dc5943495420307250cee6b",
          "sha1": "aabd37176198b4e18059c04d1654a1cbc85b546f",
          "md5": "96126c963cd01b4472f665b82a3117bb"
        }
      ]
    }
  ]
}
