{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "kanban",
    "version": "0.0.1.22012615-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "b3br7u4ednamndnvyx2cqya6du"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kanban-0.0.1.22012615-SNAPSHOT.aar",
          "url": "kanban-0.0.1.22012615-20220126.070905-1.aar",
          "size": 44856,
          "sha512": "307a535647d5a41f9f151b3a49b417b4e6451e8844c8f57ec7ebedda199033f52f92dc562462096b2c41688e55dc66870d3775f4251ecefa2a2e1dabea35740f",
          "sha256": "7f9b5027849d02a217ae9901fd620397c906e78e0600f6281b2c8e67c8f2065b",
          "sha1": "361aeb9bdaa0c01f95671b4ba33b51168e9b0bef",
          "md5": "aa42c24bf69e6ef1d2187df68f8b23ec"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kanban-0.0.1.22012615-SNAPSHOT.aar",
          "url": "kanban-0.0.1.22012615-20220126.070905-1.aar",
          "size": 44856,
          "sha512": "307a535647d5a41f9f151b3a49b417b4e6451e8844c8f57ec7ebedda199033f52f92dc562462096b2c41688e55dc66870d3775f4251ecefa2a2e1dabea35740f",
          "sha256": "7f9b5027849d02a217ae9901fd620397c906e78e0600f6281b2c8e67c8f2065b",
          "sha1": "361aeb9bdaa0c01f95671b4ba33b51168e9b0bef",
          "md5": "aa42c24bf69e6ef1d2187df68f8b23ec"
        }
      ]
    }
  ]
}
