{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.23120103-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.23120103-SNAPSHOT.aar",
          "url": "common-0.0.9.23120103-SNAPSHOT.aar",
          "size": 56181,
          "sha512": "044dd491f12679b49e47090f4fa33fb6a35fd75cf61058af47e0eb9d742130ab7e28c60efdf819b675d7f204202f9b0ab6edc076452219500fdab0656ae88755",
          "sha256": "c07f7b5066bbc66bae603accb9c1e58b65a810ed0bc6252bf3887968c9bee0c8",
          "sha1": "2778eee429ce587bafb1294dec93eaee65a890e1",
          "md5": "802f90869eaeb3d30bbb81eff67d5f86"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.23120103-SNAPSHOT.aar",
          "url": "common-0.0.9.23120103-SNAPSHOT.aar",
          "size": 56181,
          "sha512": "044dd491f12679b49e47090f4fa33fb6a35fd75cf61058af47e0eb9d742130ab7e28c60efdf819b675d7f204202f9b0ab6edc076452219500fdab0656ae88755",
          "sha256": "c07f7b5066bbc66bae603accb9c1e58b65a810ed0bc6252bf3887968c9bee0c8",
          "sha1": "2778eee429ce587bafb1294dec93eaee65a890e1",
          "md5": "802f90869eaeb3d30bbb81eff67d5f86"
        }
      ]
    }
  ]
}
