{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21101500-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yv2ayjvkrvbwnaqejymvu3ckha"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21101500-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21101500-20211014.163427-1.aar",
          "size": 139644,
          "sha512": "301c3c8ff367504ec70d7d0669673196bf73178afaa55cd6b2d5806fc40c65b7523ffd212f53ae791676b437550fb863188b3e9338d6d57c15021de5b5d34f4c",
          "sha256": "8d0262228128e92abe3afb9cce1a0754511c777ad93fc12d3e1a9a43b7d5a7e5",
          "sha1": "995ad33edb6067d7f2be8b699105d88c4773a957",
          "md5": "0a1bf201469c5a4403e934dc82dcde7d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21101500-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21101500-20211014.163427-1.aar",
          "size": 139644,
          "sha512": "301c3c8ff367504ec70d7d0669673196bf73178afaa55cd6b2d5806fc40c65b7523ffd212f53ae791676b437550fb863188b3e9338d6d57c15021de5b5d34f4c",
          "sha256": "8d0262228128e92abe3afb9cce1a0754511c777ad93fc12d3e1a9a43b7d5a7e5",
          "sha1": "995ad33edb6067d7f2be8b699105d88c4773a957",
          "md5": "0a1bf201469c5a4403e934dc82dcde7d"
        }
      ]
    }
  ]
}
