{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ikey2i24e5hv3kjsxaogz5jx4e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5.aar",
          "url": "common-0.0.5.aar",
          "size": 36198,
          "sha512": "1774fb95d78ef60e69566b2e91e130763f0c029ed792c5aed45f3e08b4b336ed3fc2ed8419632d6442d8db005d451cd08adacc67e7fbf99c4aff7f102681a263",
          "sha256": "62fb50c548265ca21a11d97f81bcf1885f6c60b06d9d01a5fe17c95ccae204e7",
          "sha1": "b161664fe80e228cbb5a4437ebd10544b048091b",
          "md5": "4ab48c45cac20ff6c792a574a2de9a1f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5.aar",
          "url": "common-0.0.5.aar",
          "size": 36198,
          "sha512": "1774fb95d78ef60e69566b2e91e130763f0c029ed792c5aed45f3e08b4b336ed3fc2ed8419632d6442d8db005d451cd08adacc67e7fbf99c4aff7f102681a263",
          "sha256": "62fb50c548265ca21a11d97f81bcf1885f6c60b06d9d01a5fe17c95ccae204e7",
          "sha1": "b161664fe80e228cbb5a4437ebd10544b048091b",
          "md5": "4ab48c45cac20ff6c792a574a2de9a1f"
        }
      ]
    }
  ]
}
