{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "widgets",
    "version": "0.0.1.22071000-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pcby3zaq6zapdam2qr234sgiky"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.22071000-SNAPSHOT.aar",
          "url": "widgets-0.0.1.22071000-20220709.160908-1.aar",
          "size": 28139,
          "sha512": "78f3e405229b7318c7b711c5fc0b5ae869b996defceed4529b96e7cac87124a1f7c23832818204cebbb4b242e025fd3e5498a97e0168b75a8d912304f73eba3c",
          "sha256": "80a49744a24437530c2dee6e63613ada0edde72ee4b2ef8b9b22a3f8d91cbe13",
          "sha1": "2e4eb4bdd6d450c1f3d6da35d4bebb482e7acf94",
          "md5": "eaf30e24c6bb6298fe46fa28ff85bada"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.22071000-SNAPSHOT.aar",
          "url": "widgets-0.0.1.22071000-20220709.160908-1.aar",
          "size": 28139,
          "sha512": "78f3e405229b7318c7b711c5fc0b5ae869b996defceed4529b96e7cac87124a1f7c23832818204cebbb4b242e025fd3e5498a97e0168b75a8d912304f73eba3c",
          "sha256": "80a49744a24437530c2dee6e63613ada0edde72ee4b2ef8b9b22a3f8d91cbe13",
          "sha1": "2e4eb4bdd6d450c1f3d6da35d4bebb482e7acf94",
          "md5": "eaf30e24c6bb6298fe46fa28ff85bada"
        }
      ]
    }
  ]
}
