{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.2210290201-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "luypawox3nfuxgwpqpvjsteexi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2210290201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2210290201-20221028.182812-1.aar",
          "size": 171817,
          "sha512": "07c7fac7227a5b6c21bfe1c2252c362c82416b05902535351d840b8cba09d2a3eb34afdc33f4da450f6e3a5e3dc9e24c13f236a1dfbace30776047d8f65959de",
          "sha256": "a3551c357f015924eb84424a4a8edc9c8f0d766d53e5e6a2fd057b335c6b7ff5",
          "sha1": "8be1b400aa806b074ac5b0b91d3373152d1461d1",
          "md5": "a45c056fd9b5c40185ee00f0bd727096"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.2210290201-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.2210290201-20221028.182812-1.aar",
          "size": 171817,
          "sha512": "07c7fac7227a5b6c21bfe1c2252c362c82416b05902535351d840b8cba09d2a3eb34afdc33f4da450f6e3a5e3dc9e24c13f236a1dfbace30776047d8f65959de",
          "sha256": "a3551c357f015924eb84424a4a8edc9c8f0d766d53e5e6a2fd057b335c6b7ff5",
          "sha1": "8be1b400aa806b074ac5b0b91d3373152d1461d1",
          "md5": "a45c056fd9b5c40185ee00f0bd727096"
        }
      ]
    }
  ]
}
