{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21092316-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "q7ewmeaj5fckvam5roxnh62qpq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21092316-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21092316-20210923.080338-1.aar",
          "size": 138323,
          "sha512": "6ba6dc32a332fe29ef072f78732e49c3f23ac30825eaafa16b1bcf77fdd2a3e396fff076d52b790674a3b58f2c172c31e7ec5524fd2423573013e3c311d92ad3",
          "sha256": "d6ad47e4f2b8e1463acdb137cd995a98d2370692846410d708310b6b05318fdd",
          "sha1": "48b5515da39e28d1a962cd429c955ac1c3aea30e",
          "md5": "998bed744e01c51875a83cc745b4840d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21092316-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21092316-20210923.080338-1.aar",
          "size": 138323,
          "sha512": "6ba6dc32a332fe29ef072f78732e49c3f23ac30825eaafa16b1bcf77fdd2a3e396fff076d52b790674a3b58f2c172c31e7ec5524fd2423573013e3c311d92ad3",
          "sha256": "d6ad47e4f2b8e1463acdb137cd995a98d2370692846410d708310b6b05318fdd",
          "sha1": "48b5515da39e28d1a962cd429c955ac1c3aea30e",
          "md5": "998bed744e01c51875a83cc745b4840d"
        }
      ]
    }
  ]
}
