{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "widgets",
    "version": "0.0.1.22092822-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "4zayduhcyzglxldhhmqj4arsey"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.22092822-SNAPSHOT.aar",
          "url": "widgets-0.0.1.22092822-20220928.144410-1.aar",
          "size": 35832,
          "sha512": "a4207192946f7d3749d21eb76fcdba145721aec0b84f45d5782c8582c10853aedae4e4c33dbfa1b023334a91d497293c805a1aec46134578658e6372ac1fc5cd",
          "sha256": "ee2640b74ae6e5bf3dd9c7c2566f91ab3dcaa7d04e06b6ac1f14468fe9d0861d",
          "sha1": "b3b6292dccbeb60374b48d536897ea3ea6ea2db3",
          "md5": "a123056cfec5990816a864c1b7d5be04"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.22092822-SNAPSHOT.aar",
          "url": "widgets-0.0.1.22092822-20220928.144410-1.aar",
          "size": 35832,
          "sha512": "a4207192946f7d3749d21eb76fcdba145721aec0b84f45d5782c8582c10853aedae4e4c33dbfa1b023334a91d497293c805a1aec46134578658e6372ac1fc5cd",
          "sha256": "ee2640b74ae6e5bf3dd9c7c2566f91ab3dcaa7d04e06b6ac1f14468fe9d0861d",
          "sha1": "b3b6292dccbeb60374b48d536897ea3ea6ea2db3",
          "md5": "a123056cfec5990816a864c1b7d5be04"
        }
      ]
    }
  ]
}
