{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22012500-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5e6afxqzeffv3oudvettehcq3e"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012500-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012500-20220124.160029-1.aar",
          "size": 120002,
          "sha512": "2d6642b81df1320c6e703b2475c4e8d19fd2111ef144852032adaa0f8b2bcab31184d0db059037c5eecfec03a234b7f9ad0c54c6692a3ea11cbcc44069908430",
          "sha256": "bc9b7c07e2f505e8a6ac0dc81b972a19f1c2da5261f1239bc1b2e65d5010004b",
          "sha1": "cf00cd2397c555dcb7441b20a58f53c4966f63f2",
          "md5": "87b0de58d7c797d430cdbcd084ecf085"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012500-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012500-20220124.160029-1.aar",
          "size": 120002,
          "sha512": "2d6642b81df1320c6e703b2475c4e8d19fd2111ef144852032adaa0f8b2bcab31184d0db059037c5eecfec03a234b7f9ad0c54c6692a3ea11cbcc44069908430",
          "sha256": "bc9b7c07e2f505e8a6ac0dc81b972a19f1c2da5261f1239bc1b2e65d5010004b",
          "sha1": "cf00cd2397c555dcb7441b20a58f53c4966f63f2",
          "md5": "87b0de58d7c797d430cdbcd084ecf085"
        }
      ]
    }
  ]
}
