{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.22070923-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cyfuwpv2uzhi3gyqvr5zwha2oi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.22070923-SNAPSHOT.aar",
          "url": "common-0.0.9.22070923-20220709.153728-1.aar",
          "size": 56000,
          "sha512": "17d329a841de9f85fb4a21e9ddf6cde474420b4fe9a624bcc0f6d8032c1a07f222a2a8e5b9ea1217e603f75b5d753d266f214bd42ffbe68b472e9065b723bd9c",
          "sha256": "c77e81c21479329b444dbf269c2616f04d8bbb6d96417b720922a529f957fbfe",
          "sha1": "4970bd1f76a8d081346eb14f98b8a51992c3947d",
          "md5": "a1f7671717d5d0942f102ef02d3d58d4"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.22070923-SNAPSHOT.aar",
          "url": "common-0.0.9.22070923-20220709.153728-1.aar",
          "size": 56000,
          "sha512": "17d329a841de9f85fb4a21e9ddf6cde474420b4fe9a624bcc0f6d8032c1a07f222a2a8e5b9ea1217e603f75b5d753d266f214bd42ffbe68b472e9065b723bd9c",
          "sha256": "c77e81c21479329b444dbf269c2616f04d8bbb6d96417b720922a529f957fbfe",
          "sha1": "4970bd1f76a8d081346eb14f98b8a51992c3947d",
          "md5": "a1f7671717d5d0942f102ef02d3d58d4"
        }
      ]
    }
  ]
}
