{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012102-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jfy5hkks7rdgddhgy6lj3zza7y"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012102-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012102-20210120.180336-1.aar",
          "size": 44267,
          "sha512": "160c4e51baa3656d81b7abfa5e5788a36506d6c318bf117de2aa28eeb90e29ddfc1e6ce9742013777e8650f0a7c155a6d5b54cc5a0d6f4ec4ee82d4650e49e32",
          "sha256": "eec60ebf0e0b35b88e4612852472147f218c0855bbb5020981b9a089a1437298",
          "sha1": "970f1f058673dc14cd30e1af739b2822d4ab6eb2",
          "md5": "dfcabab07d326c02f7c0efc8b7e75794"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012102-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012102-20210120.180336-1.aar",
          "size": 44267,
          "sha512": "160c4e51baa3656d81b7abfa5e5788a36506d6c318bf117de2aa28eeb90e29ddfc1e6ce9742013777e8650f0a7c155a6d5b54cc5a0d6f4ec4ee82d4650e49e32",
          "sha256": "eec60ebf0e0b35b88e4612852472147f218c0855bbb5020981b9a089a1437298",
          "sha1": "970f1f058673dc14cd30e1af739b2822d4ab6eb2",
          "md5": "dfcabab07d326c02f7c0efc8b7e75794"
        }
      ]
    }
  ]
}
