{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jan6oighsbeh5f5zaj7czlqku4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.8-SNAPSHOT.aar",
          "url": "common-0.0.8-20210112.094829-1.aar",
          "size": 48763,
          "sha512": "5fe313fa87691f421aa8bfd632eaba0241361b307a9da87c50425fc1fc71c6ebdb9da80d6a7b04ed88611cd124c848089dd1883f78ae9a7100bb693fcffad1e6",
          "sha256": "f1c0f9b01fc1821d2088f2dc0cd95684686b163cf52cce6c1b671ad8cc45e505",
          "sha1": "fa13546ebc3a272a5f19df68c1ddeaec69e99852",
          "md5": "40a37b8cc6a519f4e05cbcbe3e9974ca"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.8-SNAPSHOT.aar",
          "url": "common-0.0.8-20210112.094829-1.aar",
          "size": 48763,
          "sha512": "5fe313fa87691f421aa8bfd632eaba0241361b307a9da87c50425fc1fc71c6ebdb9da80d6a7b04ed88611cd124c848089dd1883f78ae9a7100bb693fcffad1e6",
          "sha256": "f1c0f9b01fc1821d2088f2dc0cd95684686b163cf52cce6c1b671ad8cc45e505",
          "sha1": "fa13546ebc3a272a5f19df68c1ddeaec69e99852",
          "md5": "40a37b8cc6a519f4e05cbcbe3e9974ca"
        }
      ]
    }
  ]
}
