{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.21110717-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "viplyji6zzbfpdpaem27uc4lrq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110717-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110717-20211107.081901-1.aar",
          "size": 120001,
          "sha512": "2a69defafb14e9f8fab62da368a72e7e66ce53dfe7dd99d5fe532a7b2b93007e92baa7fc7e3ffee5c6108061e15bc1b961563ef0cbb785c1cf1339f933ea5e6c",
          "sha256": "6150fdcbb729b849880275155aa5c3d93997d5a8b80f4a8a7a97f378a7665015",
          "sha1": "e1091a143b20315d5d0d3e488d7f058cb39dce57",
          "md5": "014af2cc1026ad8b895768f67d15e37d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110717-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110717-20211107.081901-1.aar",
          "size": 120001,
          "sha512": "2a69defafb14e9f8fab62da368a72e7e66ce53dfe7dd99d5fe532a7b2b93007e92baa7fc7e3ffee5c6108061e15bc1b961563ef0cbb785c1cf1339f933ea5e6c",
          "sha256": "6150fdcbb729b849880275155aa5c3d93997d5a8b80f4a8a7a97f378a7665015",
          "sha1": "e1091a143b20315d5d0d3e488d7f058cb39dce57",
          "md5": "014af2cc1026ad8b895768f67d15e37d"
        }
      ]
    }
  ]
}
