{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22072502-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sybdjrssuvf6zotjnn4caybcuu"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22072502-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22072502-20220724.180733-1.aar",
          "size": 164151,
          "sha512": "baa2f488b0cfb3e0ee31a7bc71c6d86d5b4323b2bcf94805ebe4b21611f1956688ca4b34ba0b621c41793df1475acd5bfdb3b54a65c9e234cf605a261bc251ec",
          "sha256": "71ed85b88085b5c65662c6607eb7d3cd3a2b6fca19d32006da78bd412e486475",
          "sha1": "413d737e8b14f2c9565938aa979282bbfbcabbf3",
          "md5": "31336258a63bd48b4a49ab6fa1122136"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22071000-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22072502-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22072502-20220724.180733-1.aar",
          "size": 164151,
          "sha512": "baa2f488b0cfb3e0ee31a7bc71c6d86d5b4323b2bcf94805ebe4b21611f1956688ca4b34ba0b621c41793df1475acd5bfdb3b54a65c9e234cf605a261bc251ec",
          "sha256": "71ed85b88085b5c65662c6607eb7d3cd3a2b6fca19d32006da78bd412e486475",
          "sha1": "413d737e8b14f2c9565938aa979282bbfbcabbf3",
          "md5": "31336258a63bd48b4a49ab6fa1122136"
        }
      ]
    }
  ]
}
