{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21062703-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cf7eaoplqveixjbpmcbexm4lha"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21062703-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21062703-20210626.192751-1.aar",
          "size": 48253,
          "sha512": "35c4b4357ae74e8be8d1b1ce9d5819a20bd9ba88378192b664137afeaa26d462b425b14874af94a668a73bd75dbfc8b146c1e9568821bbc76adb4ab96e3d173e",
          "sha256": "3037a99f965b916c0543bbe9dfb9bd960015003f53b159bb81ca3f3930b9e2e6",
          "sha1": "05945953c62e02fef98dffe3a151a40de544c50c",
          "md5": "3ee9d33edee75c10e5080a6e4e46683a"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21062703-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21062703-20210626.192751-1.aar",
          "size": 48253,
          "sha512": "35c4b4357ae74e8be8d1b1ce9d5819a20bd9ba88378192b664137afeaa26d462b425b14874af94a668a73bd75dbfc8b146c1e9568821bbc76adb4ab96e3d173e",
          "sha256": "3037a99f965b916c0543bbe9dfb9bd960015003f53b159bb81ca3f3930b9e2e6",
          "sha1": "05945953c62e02fef98dffe3a151a40de544c50c",
          "md5": "3ee9d33edee75c10e5080a6e4e46683a"
        }
      ]
    }
  ]
}
