{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tmn4rnkw2veqvafypzdxce6a6y"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.2.aar",
          "url": "recyclerview-0.9.2.aar",
          "size": 104475,
          "sha512": "0cc8ccdaf29a3d3aeecfb170acb3e9829e5dd653d2e71bf00c8a227f3b1b4ba71bff530253ca97a79ea1206b7ad88efb94a30cffd295c82e79ef94fe8205e6f5",
          "sha256": "9b06518bed545b7ddf6cfdcf0d817eb8469592978c6155c5f780d9057d88be23",
          "sha1": "c15a5df1a46c7b6cee1cde5fe8b24e5eb15e9b48",
          "md5": "037c89c0ef62c4e2b9f9abc82c0e4c1d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.2.aar",
          "url": "recyclerview-0.9.2.aar",
          "size": 104475,
          "sha512": "0cc8ccdaf29a3d3aeecfb170acb3e9829e5dd653d2e71bf00c8a227f3b1b4ba71bff530253ca97a79ea1206b7ad88efb94a30cffd295c82e79ef94fe8205e6f5",
          "sha256": "9b06518bed545b7ddf6cfdcf0d817eb8469592978c6155c5f780d9057d88be23",
          "sha1": "c15a5df1a46c7b6cee1cde5fe8b24e5eb15e9b48",
          "md5": "037c89c0ef62c4e2b9f9abc82c0e4c1d"
        }
      ]
    }
  ]
}
