{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ojm4gvdnanf6fni5y5ms5xywcq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.090931-3.aar",
          "size": 128396,
          "sha512": "72e4e48f57e1c385df51f241cc5404c07d9c8103600115d489f94e5ec9dad67f338c0b12af1ad993ed2d527a94dc8e52fbcd52ac98cae2a906e0dc10c446cafd",
          "sha256": "6cbdfceafce6d05383bc8fae5c307710b477888bcff38e543ed722e74e0e7e52",
          "sha1": "693fef5d8e49b63bc3aafe14327457539d42b7d8",
          "md5": "215c8195797390307ac3719ed70b27e6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.090931-3.aar",
          "size": 128396,
          "sha512": "72e4e48f57e1c385df51f241cc5404c07d9c8103600115d489f94e5ec9dad67f338c0b12af1ad993ed2d527a94dc8e52fbcd52ac98cae2a906e0dc10c446cafd",
          "sha256": "6cbdfceafce6d05383bc8fae5c307710b477888bcff38e543ed722e74e0e7e52",
          "sha1": "693fef5d8e49b63bc3aafe14327457539d42b7d8",
          "md5": "215c8195797390307ac3719ed70b27e6"
        }
      ]
    }
  ]
}
