{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22012522-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ftfwyoajwzhadmlyu2diwtxrii"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012522-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012522-20220125.140221-1.aar",
          "size": 121677,
          "sha512": "5e0bb3c34c30e782935b17ffb529556e71de51ff10a155682bfbb0c870dd7b728ee401c7f042e55d263d6b736df9b6b999ad22cc7d42dba11cda46cb311ae7da",
          "sha256": "a107d37fc4ad591c797ea9a0cde4bda998850faa239e0c49243c5f4f28a12b63",
          "sha1": "0a85888fec3de971ea3afe9a7ae068fac492e796",
          "md5": "788fafec4b5b70febfd4a531d96f80b7"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012522-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012522-20220125.140221-1.aar",
          "size": 121677,
          "sha512": "5e0bb3c34c30e782935b17ffb529556e71de51ff10a155682bfbb0c870dd7b728ee401c7f042e55d263d6b736df9b6b999ad22cc7d42dba11cda46cb311ae7da",
          "sha256": "a107d37fc4ad591c797ea9a0cde4bda998850faa239e0c49243c5f4f28a12b63",
          "sha1": "0a85888fec3de971ea3afe9a7ae068fac492e796",
          "md5": "788fafec4b5b70febfd4a531d96f80b7"
        }
      ]
    }
  ]
}
