{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21033102-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cads53gqgnhvtgvqrwomeh2uem"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21033102-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21033102-20210330.182442-1.aar",
          "size": 136534,
          "sha512": "17a997387e1d240585c9212b8c458fdf4b1a0e7ef35e68bd5c98d10ddafcaa1d4ae1d0ec96700929838f47ba0f84fbea28ebabc0a87db7685dcf46c75adf8d85",
          "sha256": "9bf4a4cb0dd26ce7ca3e0fa03c08340d6fac695df380c1d7aa58dc7f8cf49a89",
          "sha1": "b8705a2327919637701fbbd94ad87d9012900304",
          "md5": "5418c88417ee6f78dfe6f3903bc11d08"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21033102-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21033102-20210330.182442-1.aar",
          "size": 136534,
          "sha512": "17a997387e1d240585c9212b8c458fdf4b1a0e7ef35e68bd5c98d10ddafcaa1d4ae1d0ec96700929838f47ba0f84fbea28ebabc0a87db7685dcf46c75adf8d85",
          "sha256": "9bf4a4cb0dd26ce7ca3e0fa03c08340d6fac695df380c1d7aa58dc7f8cf49a89",
          "sha1": "b8705a2327919637701fbbd94ad87d9012900304",
          "md5": "5418c88417ee6f78dfe6f3903bc11d08"
        }
      ]
    }
  ]
}
