{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012001-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hb2ve2cjgnaexmtucrxs5wis24"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012001-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012001-20210119.175723-1.aar",
          "size": 40473,
          "sha512": "d27df3c108847b4e6ccd9942e05728eb5d30292d709d95cbf1556cf57b97ec2d307db2604bb056915eebd40580b079c9ef992294b05c772e4fa9cb1f0b9a989b",
          "sha256": "5c6a812cbe4c28ac177177bd12b19221812a34c9612cc81b3c0be4efe688f1c2",
          "sha1": "74cba25a563332559c18182936471ba00614463d",
          "md5": "d654055653d0b81fadcf6e003b1eb624"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012001-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012001-20210119.175723-1.aar",
          "size": 40473,
          "sha512": "d27df3c108847b4e6ccd9942e05728eb5d30292d709d95cbf1556cf57b97ec2d307db2604bb056915eebd40580b079c9ef992294b05c772e4fa9cb1f0b9a989b",
          "sha256": "5c6a812cbe4c28ac177177bd12b19221812a34c9612cc81b3c0be4efe688f1c2",
          "sha1": "74cba25a563332559c18182936471ba00614463d",
          "md5": "d654055653d0b81fadcf6e003b1eb624"
        }
      ]
    }
  ]
}
