{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rnyrtfpcy5cizlbi4k7jcfiium"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20210112.094958-6.aar",
          "size": 134491,
          "sha512": "0c651b03d3cd10d9f3642890f46830b6f45e109a4864eb39bee3687258b5af943d68fc4ac122911c7070acf2ef124ae8c5c1f9b333057f6ae2539f4caf6d0a22",
          "sha256": "6a874d6d9834e003f546e505a5644e18d04e9f0f421798040493e0bce1d66c34",
          "sha1": "af6980dfea4ec2c1618f8a06d5aef7889e956bf2",
          "md5": "3f8d73c1f730d3c7da7aab716017d7d1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.8-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20210112.094958-6.aar",
          "size": 134491,
          "sha512": "0c651b03d3cd10d9f3642890f46830b6f45e109a4864eb39bee3687258b5af943d68fc4ac122911c7070acf2ef124ae8c5c1f9b333057f6ae2539f4caf6d0a22",
          "sha256": "6a874d6d9834e003f546e505a5644e18d04e9f0f421798040493e0bce1d66c34",
          "sha1": "af6980dfea4ec2c1618f8a06d5aef7889e956bf2",
          "md5": "3f8d73c1f730d3c7da7aab716017d7d1"
        }
      ]
    }
  ]
}
