{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "boevp3serfe35h4qbkmr2tvqgm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201019.122155-2.aar",
          "size": 31629,
          "sha512": "871694ef31d68df98bb8a4b2513ab8fe1b6df481f0036a457a9492958c01d0420b46f028f2c499fb49ca52364ad92185d0c650c052bf2d27ac75540b30778ed9",
          "sha256": "bf451e83a68439dbaf93c3fec68b4f2cf35e4cbb50c13b064ad8624133b0cec0",
          "sha1": "bcc9419ef7c3e93201e36161dc5c04193fc685aa",
          "md5": "2a7f3f9ddb9bc528840bfddbc6fcf1b4"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.5-SNAPSHOT.aar",
          "url": "common-0.0.5-20201019.122155-2.aar",
          "size": 31629,
          "sha512": "871694ef31d68df98bb8a4b2513ab8fe1b6df481f0036a457a9492958c01d0420b46f028f2c499fb49ca52364ad92185d0c650c052bf2d27ac75540b30778ed9",
          "sha256": "bf451e83a68439dbaf93c3fec68b4f2cf35e4cbb50c13b064ad8624133b0cec0",
          "sha1": "bcc9419ef7c3e93201e36161dc5c04193fc685aa",
          "md5": "2a7f3f9ddb9bc528840bfddbc6fcf1b4"
        }
      ]
    }
  ]
}
