{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22040815-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "o32xwgufjbfbdhcmegd4qeba5q"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22040815-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22040815-20220408.071546-1.aar",
          "size": 155309,
          "sha512": "0dd3167bd3893a0500abcc74496d4c91cebef13d3811e774237eb7ba1043ec1260b5dc548db9abab39ac4b8318a6c330b4d7658c47d5baeb090f8874b5f40cec",
          "sha256": "c1490e91034cc1ae9bbe3f488cf2064886deafd9dee13a463e2b35ed80fa127f",
          "sha1": "fb88a19282e6e58bf99a9dc73a1c4c1cea9fc9d1",
          "md5": "8075f6cd3b680bdf7a034afa5f9ddc48"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22040815-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22040815-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22040815-20220408.071546-1.aar",
          "size": 155309,
          "sha512": "0dd3167bd3893a0500abcc74496d4c91cebef13d3811e774237eb7ba1043ec1260b5dc548db9abab39ac4b8318a6c330b4d7658c47d5baeb090f8874b5f40cec",
          "sha256": "c1490e91034cc1ae9bbe3f488cf2064886deafd9dee13a463e2b35ed80fa127f",
          "sha1": "fb88a19282e6e58bf99a9dc73a1c4c1cea9fc9d1",
          "md5": "8075f6cd3b680bdf7a034afa5f9ddc48"
        }
      ]
    }
  ]
}
