{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.23022223-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "it7kxsvxzzbabaicmz23qf7jdq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022223-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022223-20230222.151921-1.aar",
          "size": 185751,
          "sha512": "7af44905d151c4d485f5467cc62dd5c60516a15469df024eccbaa04367713ffde4cb710d656d242acddee7ba9fdd102e9f336afc15a7da2343c1a2deed83659f",
          "sha256": "23920a06cb5f035ad6edd95a006a8b807a23b8ee33fa9451b9713c363a6b29d2",
          "sha1": "89d6fa258aeb1a185de2608a0aaffe5512180e2c",
          "md5": "c483edfca65de199f0433117b048aea6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022223-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022223-20230222.151921-1.aar",
          "size": 185751,
          "sha512": "7af44905d151c4d485f5467cc62dd5c60516a15469df024eccbaa04367713ffde4cb710d656d242acddee7ba9fdd102e9f336afc15a7da2343c1a2deed83659f",
          "sha256": "23920a06cb5f035ad6edd95a006a8b807a23b8ee33fa9451b9713c363a6b29d2",
          "sha1": "89d6fa258aeb1a185de2608a0aaffe5512180e2c",
          "md5": "c483edfca65de199f0433117b048aea6"
        }
      ]
    }
  ]
}
