{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012100-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sr6jss7gcfaopm6qvzgreb43fy"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012100-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012100-20210120.165611-1.aar",
          "size": 42475,
          "sha512": "2ffd114ebfe242f903bd369f6859c25296f4289f182839a49b8421e9bbeeb38e0251cc0374f56518d52a7e14531f33e93a1af05825cfd2bdc57c1e0aefb9e070",
          "sha256": "400239f20e0b0c4c21225623d55f2c54bf7b23c8254c96faf5662c803a47abb4",
          "sha1": "226f306dc79c382363b2e9c5e7302d62a2c8a97d",
          "md5": "4e5bb5bbaa6e513aab8a113da68dc56d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012100-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012100-20210120.165611-1.aar",
          "size": 42475,
          "sha512": "2ffd114ebfe242f903bd369f6859c25296f4289f182839a49b8421e9bbeeb38e0251cc0374f56518d52a7e14531f33e93a1af05825cfd2bdc57c1e0aefb9e070",
          "sha256": "400239f20e0b0c4c21225623d55f2c54bf7b23c8254c96faf5662c803a47abb4",
          "sha1": "226f306dc79c382363b2e9c5e7302d62a2c8a97d",
          "md5": "4e5bb5bbaa6e513aab8a113da68dc56d"
        }
      ]
    }
  ]
}
