{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22012500-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "x6oyumtdcfhezhkoomluesd47e"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012500-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012500-20220124.163216-2.aar",
          "size": 119569,
          "sha512": "a355fb7ff661adc2e5ba3f969bcc21b786589ab926862ce17773d843cdaa68ecddffdbe196213568bf0aab0b3a23296e21cee427d084ce4c426d33fb49f96275",
          "sha256": "3a85c6192737fcf77c5ed429f74239e5d239072d6f90de9e9b79b2ba206f83bd",
          "sha1": "c5658c981573eabcc7da723a73f96f7c3bcf46d1",
          "md5": "4d9aca82cddb49b5724323d0c2ec4dfb"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012500-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012500-20220124.163216-2.aar",
          "size": 119569,
          "sha512": "a355fb7ff661adc2e5ba3f969bcc21b786589ab926862ce17773d843cdaa68ecddffdbe196213568bf0aab0b3a23296e21cee427d084ce4c426d33fb49f96275",
          "sha256": "3a85c6192737fcf77c5ed429f74239e5d239072d6f90de9e9b79b2ba206f83bd",
          "sha1": "c5658c981573eabcc7da723a73f96f7c3bcf46d1",
          "md5": "4d9aca82cddb49b5724323d0c2ec4dfb"
        }
      ]
    }
  ]
}
