{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pkmddgr7gneaxadjjwj3po5ni4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.175813-6.aar",
          "size": 127014,
          "sha512": "4b99bbee8db414ba69f7072323c5ae1d9d611fd22885a6e8cee95d8769c8dc1b53573448a3b40d2b88b5c06f52b9de9b9bd195d5bc25dfe3b223e61d29a57c8d",
          "sha256": "c63146ea520ca52db5f589fabe52a13177a1bfab63085d2b0701e2ae84a27eab",
          "sha1": "64d1a80520ee857e1a78c2b272aba4ed8d4c3d11",
          "md5": "0fe0d6aa84aee3b4c37cf9f6bcc1ab76"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.6-SNAPSHOT.aar",
          "url": "recyclerview-0.9.6-20201025.175813-6.aar",
          "size": 127014,
          "sha512": "4b99bbee8db414ba69f7072323c5ae1d9d611fd22885a6e8cee95d8769c8dc1b53573448a3b40d2b88b5c06f52b9de9b9bd195d5bc25dfe3b223e61d29a57c8d",
          "sha256": "c63146ea520ca52db5f589fabe52a13177a1bfab63085d2b0701e2ae84a27eab",
          "sha1": "64d1a80520ee857e1a78c2b272aba4ed8d4c3d11",
          "md5": "0fe0d6aa84aee3b4c37cf9f6bcc1ab76"
        }
      ]
    }
  ]
}
