{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tgvn2hedjrbaxow7xrgw4lucxu"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201101.093546-1.aar",
          "size": 132593,
          "sha512": "626469b4e94730bda4e3f158c96325dd8ca9835ae02a68c0ef5b39d3c5f16b242dc782809746f3e15c4c93dff06271fcba5cb387d49184c2b382386cb1083384",
          "sha256": "caa4e16bdfe5efa929c5def30fdc70fc091f81ca1f4c636af3ccb099e33c2251",
          "sha1": "15494c756190b28c85f3229481d62c720869a006",
          "md5": "0fd72ea520bf47e30f0b0a8ad42fe871"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7-20201101.093546-1.aar",
          "size": 132593,
          "sha512": "626469b4e94730bda4e3f158c96325dd8ca9835ae02a68c0ef5b39d3c5f16b242dc782809746f3e15c4c93dff06271fcba5cb387d49184c2b382386cb1083384",
          "sha256": "caa4e16bdfe5efa929c5def30fdc70fc091f81ca1f4c636af3ccb099e33c2251",
          "sha1": "15494c756190b28c85f3229481d62c720869a006",
          "md5": "0fd72ea520bf47e30f0b0a8ad42fe871"
        }
      ]
    }
  ]
}
