{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22122223-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vc4pakl3evatdov4vxzljhszhm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22122223-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22122223-20221222.150856-1.aar",
          "size": 176049,
          "sha512": "c2989e466afc6967804d4a937cfaef2d6d1193171c43d81c730010795b79738fab59500ffafba22a5307d03dd0cd0b263aa041a14c0e357a2ff43b3a9f3f3bb2",
          "sha256": "0bcd56e1bc437571da778f30bb7e634865acdfb60288a306668a394e7b479846",
          "sha1": "e8d6a0cbafd28e5a222bf4e5b8451ee8ac1e9abb",
          "md5": "17eb96b64048a65dd0578ec05a8243d9"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22070923-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22122223-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22122223-20221222.150856-1.aar",
          "size": 176049,
          "sha512": "c2989e466afc6967804d4a937cfaef2d6d1193171c43d81c730010795b79738fab59500ffafba22a5307d03dd0cd0b263aa041a14c0e357a2ff43b3a9f3f3bb2",
          "sha256": "0bcd56e1bc437571da778f30bb7e634865acdfb60288a306668a394e7b479846",
          "sha1": "e8d6a0cbafd28e5a222bf4e5b8451ee8ac1e9abb",
          "md5": "17eb96b64048a65dd0578ec05a8243d9"
        }
      ]
    }
  ]
}
