{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21091719-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tus5uf6bnvd2tahhxjkvv2t53y"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21091719-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21091719-20210917.114127-1.aar",
          "size": 138301,
          "sha512": "0e7923686956b965e3ccc509f62e509b21e823144dd8c21981678671a35b7793f74a68f5d9a9e466e35c9995ca07e6d981efc462c89069dffd0a2ce7f2d1aa5a",
          "sha256": "0820e03a001a0ca8a9252cb79b9e3373d4994f6d6b02855b84477ac33c4ecb09",
          "sha1": "abfe411a91e8dc81bd6afbab9d2342fa6aedf082",
          "md5": "6ed7abce07d7dd57cf9c9936e9de7cf5"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21091719-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21091719-20210917.114127-1.aar",
          "size": 138301,
          "sha512": "0e7923686956b965e3ccc509f62e509b21e823144dd8c21981678671a35b7793f74a68f5d9a9e466e35c9995ca07e6d981efc462c89069dffd0a2ce7f2d1aa5a",
          "sha256": "0820e03a001a0ca8a9252cb79b9e3373d4994f6d6b02855b84477ac33c4ecb09",
          "sha1": "abfe411a91e8dc81bd6afbab9d2342fa6aedf082",
          "md5": "6ed7abce07d7dd57cf9c9936e9de7cf5"
        }
      ]
    }
  ]
}
