{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.23011719-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "t7e6b5nq7nd6xdwgrlgv37jley"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23011719-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23011719-20230117.113747-1.aar",
          "size": 176195,
          "sha512": "d8de42fb93729dbd1e7d03c26e6064b1910a93d5ed26f6cca5224d388df95bafe313150a3c97729469cc410bbe62a917b144ef6a233fc421eaf601eaeec254bf",
          "sha256": "1f3181974c7708f2699ff7534f3d665e07fb782804307d492a4b213f37ebe89e",
          "sha1": "83233e60cbb55af01b67dbbf4e44e1976d1a8b5f",
          "md5": "0d4750d63917a75f6ec81c37eac8d0c8"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23011719-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23011719-20230117.113747-1.aar",
          "size": 176195,
          "sha512": "d8de42fb93729dbd1e7d03c26e6064b1910a93d5ed26f6cca5224d388df95bafe313150a3c97729469cc410bbe62a917b144ef6a233fc421eaf601eaeec254bf",
          "sha256": "1f3181974c7708f2699ff7534f3d665e07fb782804307d492a4b213f37ebe89e",
          "sha1": "83233e60cbb55af01b67dbbf4e44e1976d1a8b5f",
          "md5": "0d4750d63917a75f6ec81c37eac8d0c8"
        }
      ]
    }
  ]
}
