{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.23052822-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "5iklditv65bwrmkak6pye7idmi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23052822-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23052822-20230528.141534-1.aar",
          "size": 186894,
          "sha512": "17a669d6d86d24c19243bd65c6a31151d9f0c6ae038fc4c92e6c16e859a5580a84ad0bea9b917a50194dfccd274c7fa68c2919784f2305d520a2f0d8ee1dfdf7",
          "sha256": "50bc3978276bab723175fdc0d9231c99c6054d115673a4c5e40fc07495bb5b5e",
          "sha1": "6e200c21d5fdd42269f5e338dcb4bcadb8d55449",
          "md5": "4133bd8d9985e85c4f75e6182ffa7c77"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23052822-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23052822-20230528.141534-1.aar",
          "size": 186894,
          "sha512": "17a669d6d86d24c19243bd65c6a31151d9f0c6ae038fc4c92e6c16e859a5580a84ad0bea9b917a50194dfccd274c7fa68c2919784f2305d520a2f0d8ee1dfdf7",
          "sha256": "50bc3978276bab723175fdc0d9231c99c6054d115673a4c5e40fc07495bb5b5e",
          "sha1": "6e200c21d5fdd42269f5e338dcb4bcadb8d55449",
          "md5": "4133bd8d9985e85c4f75e6182ffa7c77"
        }
      ]
    }
  ]
}
