{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.9.20012116-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cwx4npzimvdnxm55vg3pjrlcqm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.9.20012116-SNAPSHOT.aar",
          "url": "common-0.0.9.20012116-20210121.085957-1.aar",
          "size": 48829,
          "sha512": "42e39bf90b58796bd8bef12c5df9fbec589cbbdab2477361a4714ecba6a6aea50b9c20bfa5cde8c219ce56054a5bbccc064e8633b20aac15547dee48c3863261",
          "sha256": "db643032f5ebfbfdea9839b0ae749401d5d5c7b663986da1adbf6ccbb2d9e5c5",
          "sha1": "94b204dc5ad30ee80a222b33c947855c408789b4",
          "md5": "87a3ae5819ec24cc5fcaa624e8094657"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.9.20012116-SNAPSHOT.aar",
          "url": "common-0.0.9.20012116-20210121.085957-1.aar",
          "size": 48829,
          "sha512": "42e39bf90b58796bd8bef12c5df9fbec589cbbdab2477361a4714ecba6a6aea50b9c20bfa5cde8c219ce56054a5bbccc064e8633b20aac15547dee48c3863261",
          "sha256": "db643032f5ebfbfdea9839b0ae749401d5d5c7b663986da1adbf6ccbb2d9e5c5",
          "sha1": "94b204dc5ad30ee80a222b33c947855c408789b4",
          "md5": "87a3ae5819ec24cc5fcaa624e8094657"
        }
      ]
    }
  ]
}
