{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.23022220-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "3fkpmpnykncf3gpzlpyzs26utm"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022220-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022220-20230222.125216-1.aar",
          "size": 185040,
          "sha512": "72f2f44d0dce3d84afd08cd7bf3fa54ad81a531615996d3d63e210aebf780141ca027abb13263b45dd1bde4d33b2404c716dcd3aa6e390520dd5d75a3bb60145",
          "sha256": "9c5b66a9dcea6186ed0abd796177852cbc9057a3c7ccde5775068e975c084ae8",
          "sha1": "aff3d4fd3155afe9e34a751f4a3e4f8bff3ac565",
          "md5": "4106909fa0ae10ca26c1c0d2b4679119"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022220-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022220-20230222.125216-1.aar",
          "size": 185040,
          "sha512": "72f2f44d0dce3d84afd08cd7bf3fa54ad81a531615996d3d63e210aebf780141ca027abb13263b45dd1bde4d33b2404c716dcd3aa6e390520dd5d75a3bb60145",
          "sha256": "9c5b66a9dcea6186ed0abd796177852cbc9057a3c7ccde5775068e975c084ae8",
          "sha1": "aff3d4fd3155afe9e34a751f4a3e4f8bff3ac565",
          "md5": "4106909fa0ae10ca26c1c0d2b4679119"
        }
      ]
    }
  ]
}
