{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.2.1.21012105-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "73mzjy5umjcdvfoaigg5q73zl4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.2.1.21012105-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012105-20210120.190518-1.aar",
          "size": 43818,
          "sha512": "4543ddf380f6641a29540a33517511fc5cc47cd7d05fbe2734d21fe271a867a3dc3c96c6c176102d3209168354f53588163d910459b164f83429519f1ddb0441",
          "sha256": "5b1fc0adcfb1ae61b27d80a7fb6dcfb744698cd9c296247c10ef27a9bd20bab3",
          "sha1": "f6bf5f39c98c1c73c5d37d37bb3a9ddfb6f64626",
          "md5": "45cc16ffd4e1a6c49ac2d23ba83e5545"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.2.1.21012105-SNAPSHOT.aar",
          "url": "json-dsl-0.2.1.21012105-20210120.190518-1.aar",
          "size": 43818,
          "sha512": "4543ddf380f6641a29540a33517511fc5cc47cd7d05fbe2734d21fe271a867a3dc3c96c6c176102d3209168354f53588163d910459b164f83429519f1ddb0441",
          "sha256": "5b1fc0adcfb1ae61b27d80a7fb6dcfb744698cd9c296247c10ef27a9bd20bab3",
          "sha1": "f6bf5f39c98c1c73c5d37d37bb3a9ddfb6f64626",
          "md5": "45cc16ffd4e1a6c49ac2d23ba83e5545"
        }
      ]
    }
  ]
}
