{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.22010701-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "a2pklr3atzf7deddvvvowv7wsi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.22010701-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.22010701-20220106.164950-1.aar",
          "size": 127496,
          "sha512": "1f9d9b779cad192c0c69c4659886314f596d8960da853b4b73fc0811644044c9b60ae47ea4c65940a1a2abfc0337b119a106a3fcc4c84b06952c589a480e58f0",
          "sha256": "61be61f909fd867c3d321d3319c128a21c239ef893dcdd72fb0338d303832422",
          "sha1": "f58d260c00bba95faca67c553ec15a0639ab6ec5",
          "md5": "c620013d6754af25542f029817ef5d0d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.22010701-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.22010701-20220106.164950-1.aar",
          "size": 127496,
          "sha512": "1f9d9b779cad192c0c69c4659886314f596d8960da853b4b73fc0811644044c9b60ae47ea4c65940a1a2abfc0337b119a106a3fcc4c84b06952c589a480e58f0",
          "sha256": "61be61f909fd867c3d321d3319c128a21c239ef893dcdd72fb0338d303832422",
          "sha1": "f58d260c00bba95faca67c553ec15a0639ab6ec5",
          "md5": "c620013d6754af25542f029817ef5d0d"
        }
      ]
    }
  ]
}
