{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "common",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jnexyqdtkraoli3fznowxgpr74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-0.0.7.aar",
          "url": "common-0.0.7.aar",
          "size": 48211,
          "sha512": "579311c59c3d1cb0ebcb1f48c3842e0e0ed5015b2da50c2a727d9d498ccf72e5945bf7a582dd96a75bf0f002bd076a27b1a35f7bba73b69f66c1c96757c1f0e8",
          "sha256": "3c17a3200912e18462b7fa9673f2964d061a0f07e9861149ae876c6b1220f85c",
          "sha1": "ba3ff79efa731b26c9bf820707fbac5a946e3143",
          "md5": "aec60bea7a35233de49ec25eadfee70a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.0.7.aar",
          "url": "common-0.0.7.aar",
          "size": 48211,
          "sha512": "579311c59c3d1cb0ebcb1f48c3842e0e0ed5015b2da50c2a727d9d498ccf72e5945bf7a582dd96a75bf0f002bd076a27b1a35f7bba73b69f66c1c96757c1f0e8",
          "sha256": "3c17a3200912e18462b7fa9673f2964d061a0f07e9861149ae876c6b1220f85c",
          "sha1": "ba3ff79efa731b26c9bf820707fbac5a946e3143",
          "md5": "aec60bea7a35233de49ec25eadfee70a"
        }
      ]
    }
  ]
}
