{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.flutter",
    "module": "nestedscrollview",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nestedscrollview-1.0.0-SNAPSHOT.aar",
          "url": "nestedscrollview-1.0.0-SNAPSHOT.aar",
          "size": 17974,
          "sha512": "69cd436cbad628817eab9337ffdccdc217ed7626b337e9a22c0a494ba8cc614aebdc2f8fcf95195a2aeede1976266ed5eb3dddb0550e9ef54aed0a19ae9440de",
          "sha256": "104e417a45091916fe468c1c1820a1ba115c37d8da8ad4fe2b45533be5dbc092",
          "sha1": "3dac4c79533885b3487c7edac8ff2802828daa95",
          "md5": "bbeaacc83e9c7d1f4d745d9561a910c3"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.worktile.flutter.module",
          "module": "flutter",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "nestedscrollview-1.0.0-SNAPSHOT.aar",
          "url": "nestedscrollview-1.0.0-SNAPSHOT.aar",
          "size": 17974,
          "sha512": "69cd436cbad628817eab9337ffdccdc217ed7626b337e9a22c0a494ba8cc614aebdc2f8fcf95195a2aeede1976266ed5eb3dddb0550e9ef54aed0a19ae9440de",
          "sha256": "104e417a45091916fe468c1c1820a1ba115c37d8da8ad4fe2b45533be5dbc092",
          "sha1": "3dac4c79533885b3487c7edac8ff2802828daa95",
          "md5": "bbeaacc83e9c7d1f4d745d9561a910c3"
        }
      ]
    }
  ]
}
