{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "0.9.7.21110718-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "x3u6uyyc2rathlb7wlj2spvs5y"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110718-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110718-20211107.091612-1.aar",
          "size": 122983,
          "sha512": "a97fbb7f7a794281fe418727a8e1923f5179fbcc79e939e3a00472ccdf7662fbee2885eaa3921f192712041f6d7eb622279b585fbcf6d0d5bb750cf7b9f56692",
          "sha256": "f2d18d835cc00ef0918874a67ab9f36559e026f39f6471e79672abb1e9c4810b",
          "sha1": "29e58352185d58a84e566172b84fdaa97d066a6a",
          "md5": "a5f4d7cd0635de44deb64b5ff93c1b28"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21082302-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-0.9.7.21110718-SNAPSHOT.aar",
          "url": "recyclerview2-0.9.7.21110718-20211107.091612-1.aar",
          "size": 122983,
          "sha512": "a97fbb7f7a794281fe418727a8e1923f5179fbcc79e939e3a00472ccdf7662fbee2885eaa3921f192712041f6d7eb622279b585fbcf6d0d5bb750cf7b9f56692",
          "sha256": "f2d18d835cc00ef0918874a67ab9f36559e026f39f6471e79672abb1e9c4810b",
          "sha1": "29e58352185d58a84e566172b84fdaa97d066a6a",
          "md5": "a5f4d7cd0635de44deb64b5ff93c1b28"
        }
      ]
    }
  ]
}
