{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pc2yopounzc5lkzc2g73r6eyke"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.0.1.aar",
          "url": "json-dsl-0.0.1.aar",
          "size": 45229,
          "sha512": "2bcea09e62d7786ca513f761663ed48a1f010dd498e07ba6f8afbe81dbee837c62fe8ff9b81273b5cbd351c099ee6da9c7086987addf8cec56f4182a56664598",
          "sha256": "9731bf2dd514e977fa7758ec46ac6483f01815184fb844644cb3edcd7195f168",
          "sha1": "592959be710ffd1ecccbd53873617fc6b2d9a1f0",
          "md5": "48c2b13b5bf29bdc7644ae5d06fcc486"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.0.1.aar",
          "url": "json-dsl-0.0.1.aar",
          "size": 45229,
          "sha512": "2bcea09e62d7786ca513f761663ed48a1f010dd498e07ba6f8afbe81dbee837c62fe8ff9b81273b5cbd351c099ee6da9c7086987addf8cec56f4182a56664598",
          "sha256": "9731bf2dd514e977fa7758ec46ac6483f01815184fb844644cb3edcd7195f168",
          "sha1": "592959be710ffd1ecccbd53873617fc6b2d9a1f0",
          "md5": "48c2b13b5bf29bdc7644ae5d06fcc486"
        }
      ]
    }
  ]
}
