{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview",
    "version": "0.9.7.21020602-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "3vgnmkovwjallkhd76l2e3w6re"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020602-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020602-20210205.181532-1.aar",
          "size": 135553,
          "sha512": "6d71322c2e6e7826a7a0775c58acc4a8f97e7a6a2a75ed86343b9359198fb4ed5eeae57f7997a986c86b10ae046e0736e0d9fa74b04cea645e510264e870f699",
          "sha256": "45013f970d35de3fab866f85c2c7752028bef11b19e45b96e4c07bdd7b300bec",
          "sha1": "ab768a29c842ab2dc94bb3605fc1dd6ada24d28f",
          "md5": "4775ed4a3357e8ac9b09861b1f65a276"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21012116-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-0.9.7.21020602-SNAPSHOT.aar",
          "url": "recyclerview-0.9.7.21020602-20210205.181532-1.aar",
          "size": 135553,
          "sha512": "6d71322c2e6e7826a7a0775c58acc4a8f97e7a6a2a75ed86343b9359198fb4ed5eeae57f7997a986c86b10ae046e0736e0d9fa74b04cea645e510264e870f699",
          "sha256": "45013f970d35de3fab866f85c2c7752028bef11b19e45b96e4c07bdd7b300bec",
          "sha1": "ab768a29c842ab2dc94bb3605fc1dd6ada24d28f",
          "md5": "4775ed4a3357e8ac9b09861b1f65a276"
        }
      ]
    }
  ]
}
