{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile",
    "module": "base",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nzu2fo556bbj5emzkcckvow2cy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-0.0.1.aar",
          "url": "base-0.0.1.aar",
          "size": 19896,
          "sha512": "6c847a4f18f717203c40334820fb4193a826b1dc6f0b01b84708cf7d06d0828aa037a3b5bafb2b0f38737c261a2b13ead778b6003403675b158c4bf6287b1a22",
          "sha256": "fa6a928a9b8198a21c4a424b63d7a5ee9163d25d6a4b46bb3a51e7e72a35ada3",
          "sha1": "aca8a558d2ad91de0a51f932b13476572d009eee",
          "md5": "15dbd33757c02916952fd0780e11182c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-0.0.1.aar",
          "url": "base-0.0.1.aar",
          "size": 19896,
          "sha512": "6c847a4f18f717203c40334820fb4193a826b1dc6f0b01b84708cf7d06d0828aa037a3b5bafb2b0f38737c261a2b13ead778b6003403675b158c4bf6287b1a22",
          "sha256": "fa6a928a9b8198a21c4a424b63d7a5ee9163d25d6a4b46bb3a51e7e72a35ada3",
          "sha1": "aca8a558d2ad91de0a51f932b13476572d009eee",
          "md5": "15dbd33757c02916952fd0780e11182c"
        }
      ]
    }
  ]
}
