{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.23022218-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cmkyuabrenewxa5agbv7lim6yy"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022218-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022218-20230222.102936-1.aar",
          "size": 184864,
          "sha512": "a29d31447530ceebcee8073496380833ea3a4966748c32f295fc9cac89d1f02aed7ec1f0a2f225ca89b64b53d874b2451710326983baea47582339e365838948",
          "sha256": "be45d18355616d75e7e04e07b7498bdf88f92bfcd9e5386130da0c7fe3b032c9",
          "sha1": "e083480404b5252ae877baa0b9c01f7e56fda713",
          "md5": "f3a822e5f7f94552c5bfdeffd6118d53"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22122613-SNAPSHOT"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22092822-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.23022218-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.23022218-20230222.102936-1.aar",
          "size": 184864,
          "sha512": "a29d31447530ceebcee8073496380833ea3a4966748c32f295fc9cac89d1f02aed7ec1f0a2f225ca89b64b53d874b2451710326983baea47582339e365838948",
          "sha256": "be45d18355616d75e7e04e07b7498bdf88f92bfcd9e5386130da0c7fe3b032c9",
          "sha1": "e083480404b5252ae877baa0b9c01f7e56fda713",
          "md5": "f3a822e5f7f94552c5bfdeffd6118d53"
        }
      ]
    }
  ]
}
