{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22012501-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "hu7ssjokufhifazgza6bt6yy3a"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012501-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012501-20220124.170547-1.aar",
          "size": 119901,
          "sha512": "845d4735aa5a1f084f6eeddf5c5e188b3608ffa1c9a4b26335a834f2721be3ef1d3fcd4971d869d17e2bfdb2fd224ba4da4efddc18e147f0e3062c639b67f983",
          "sha256": "c15950528623c31bd94a8ee854955df9266e25a3caedbbfbebd73b95165811e9",
          "sha1": "bcd0881b5121da725a0220f97da2cf67ebcd8d5c",
          "md5": "07af284efd0776325f76c85770dcd233"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.21062800-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.22011118-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22012501-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22012501-20220124.170547-1.aar",
          "size": 119901,
          "sha512": "845d4735aa5a1f084f6eeddf5c5e188b3608ffa1c9a4b26335a834f2721be3ef1d3fcd4971d869d17e2bfdb2fd224ba4da4efddc18e147f0e3062c639b67f983",
          "sha256": "c15950528623c31bd94a8ee854955df9266e25a3caedbbfbebd73b95165811e9",
          "sha1": "bcd0881b5121da725a0220f97da2cf67ebcd8d5c",
          "md5": "07af284efd0776325f76c85770dcd233"
        }
      ]
    }
  ]
}
