{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.json",
    "module": "json-dsl",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rn46uyrx2nb7pas5hwpoc7gp7e"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-dsl-0.1.0-SNAPSHOT.aar",
          "url": "json-dsl-0.1.0-20210105.171557-3.aar",
          "size": 38766,
          "sha512": "4b018b794be53f528aad88ec4a9eaf5a6982a07c6dfdddb9a58e7add5baa64e572afde4526b82e2a84c66d57f2aad5624df4ecfe91256f8c184adc9752c6460e",
          "sha256": "c5e82fb8049c69026b8c0d4d66c12122471a371381c174d2ca79ec93117eaf11",
          "sha1": "fc3d9e85578507e3e70d96fee505e49588e06fd5",
          "md5": "4c9b3036a607a44cf93a50a1aaef8ef1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "json-dsl-0.1.0-SNAPSHOT.aar",
          "url": "json-dsl-0.1.0-20210105.171557-3.aar",
          "size": 38766,
          "sha512": "4b018b794be53f528aad88ec4a9eaf5a6982a07c6dfdddb9a58e7add5baa64e572afde4526b82e2a84c66d57f2aad5624df4ecfe91256f8c184adc9752c6460e",
          "sha256": "c5e82fb8049c69026b8c0d4d66c12122471a371381c174d2ca79ec93117eaf11",
          "sha1": "fc3d9e85578507e3e70d96fee505e49588e06fd5",
          "md5": "4c9b3036a607a44cf93a50a1aaef8ef1"
        }
      ]
    }
  ]
}
