{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "recyclerview2",
    "version": "1.0.0.22062802-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ukupdqjxpvh6lpny544yp6rrcy"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22062802-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22062802-20220627.180831-1.aar",
          "size": 155462,
          "sha512": "3a5c1acbfb2852fa701aa0f24e848fbb501ee12781a0ea1cd93ca8924e7d68201f95762839996a7dfe62c1a6c8649fd426a77ee23e59d792a224f3ae853ba194",
          "sha256": "47b834832eb9ddd10871adbb0e26d5014a6e1960ef8fbae3711db372e9ab6e3b",
          "sha1": "5ba48b256dc352ef1c7a5bf29f09a00447a66905",
          "md5": "a857605aa5dfd9d12c905e8c4a7b5ef6"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile.ui",
          "module": "widgets",
          "version": {
            "requires": "0.0.1.22040815-SNAPSHOT"
          }
        },
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.220050821-SNAPSHOT"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview2-1.0.0.22062802-SNAPSHOT.aar",
          "url": "recyclerview2-1.0.0.22062802-20220627.180831-1.aar",
          "size": 155462,
          "sha512": "3a5c1acbfb2852fa701aa0f24e848fbb501ee12781a0ea1cd93ca8924e7d68201f95762839996a7dfe62c1a6c8649fd426a77ee23e59d792a224f3ae853ba194",
          "sha256": "47b834832eb9ddd10871adbb0e26d5014a6e1960ef8fbae3711db372e9ab6e3b",
          "sha1": "5ba48b256dc352ef1c7a5bf29f09a00447a66905",
          "md5": "a857605aa5dfd9d12c905e8c4a7b5ef6"
        }
      ]
    }
  ]
}
