{
  "formatVersion": "1.1",
  "component": {
    "group": "com.worktile.ui",
    "module": "widgets",
    "version": "0.0.1.21062800-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tum2wvps3vecjo7irroht7r3my"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.21062800-SNAPSHOT.aar",
          "url": "widgets-0.0.1.21062800-20210627.162534-1.aar",
          "size": 31865,
          "sha512": "550c0a150e3879d2228a1e9a1e5be573fbc4fcb52cb5ec5e541cd8f02ea8cfe2fc17ef483ab8da309a3d97fba252868bc4c09efa2e089d128404687f82014c15",
          "sha256": "56a02f301085cd2cf5faab2290c53fc11849326997a6b72f11e00b1653dfb499",
          "sha1": "ccb878723e8a065f415d998082a4a34a5c96ff16",
          "md5": "2a7cce09113b9e1de8e9f64e08f573dc"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.worktile",
          "module": "common",
          "version": {
            "requires": "0.0.9.21030519-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-0.0.1.21062800-SNAPSHOT.aar",
          "url": "widgets-0.0.1.21062800-20210627.162534-1.aar",
          "size": 31865,
          "sha512": "550c0a150e3879d2228a1e9a1e5be573fbc4fcb52cb5ec5e541cd8f02ea8cfe2fc17ef483ab8da309a3d97fba252868bc4c09efa2e089d128404687f82014c15",
          "sha256": "56a02f301085cd2cf5faab2290c53fc11849326997a6b72f11e00b1653dfb499",
          "sha1": "ccb878723e8a065f415d998082a4a34a5c96ff16",
          "md5": "2a7cce09113b9e1de8e9f64e08f573dc"
        }
      ]
    }
  ]
}
